import '../models/ipo_item.dart';

// BIST 500 — Tam hisse listesi (Kaynak: Borsa İstanbul)
// Borsa İstanbul'da 2026 itibarıyla bildirilen toplam hisse sayısı 610 civarındadır.
const int kBistListedCount = 610;

const List<Map<String, String>> _baseBistStocks = [
  {'symbol': 'A1CAP', 'name': 'A1 Capital'},
  {'symbol': 'A1YEN', 'name': 'A1 Yenilenebilir Enerji'},
  {'symbol': 'AAGYO', 'name': 'Agaoglu Avrasya GYO'},
  {'symbol': 'ACSEL', 'name': 'Aciselsan Acipayam Seluloz'},
  {'symbol': 'ADEL', 'name': 'Adel Kalemcilik'},
  {'symbol': 'ADESE', 'name': 'Adese Gayrimenkul Yatırım A.Ş.'},
  {'symbol': 'ADGYO', 'name': 'Adra GYO'},
  {'symbol': 'AEFES', 'name': 'Anadolu Efes'},
  {'symbol': 'AFYON', 'name': 'Afyon Çimento'},
  {'symbol': 'AGESA', 'name': 'Agesa Hayat Emeklilik'},
  {'symbol': 'AGHOL', 'name': 'AG Anadolu Grubu Holding'},
  {'symbol': 'AGROT', 'name': 'Agrotech Yuksek Teknoloji ve Yatırım A.Ş.'},
  {'symbol': 'AGTUR', 'name': 'Agro-Tur Tarım'},
  {'symbol': 'AGYO', 'name': 'Atakule Gayrimenkul Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'AHGAZ', 'name': 'Ahlatçı Doğal Gaz Dağıtım'},
  {'symbol': 'AHGYO', 'name': 'Ahlatcı GYO'},
  {'symbol': 'AHSGY', 'name': 'Ahes GYO'},
  {'symbol': 'AKBNK', 'name': 'Akbank T.A.Ş.'},
  {'symbol': 'AKCNS', 'name': 'Akçansa Çimento'},
  {'symbol': 'AKENR', 'name': 'Akenerji Elektrik'},
  {'symbol': 'AKFGY', 'name': 'Akfen GYO'},
  {'symbol': 'AKFIS', 'name': 'Akfen İnşaat Turizm ve Ticaret A.Ş.'},
  {'symbol': 'AKFYE', 'name': 'Akfen Yenilenebilir Enerji'},
  {'symbol': 'AKGRT', 'name': 'Aksigorta'},
  {'symbol': 'AKHAN', 'name': 'Akhan Un Fabrikası ve Tarım Ürünleri'},
  {'symbol': 'AKMGY', 'name': 'AkMerkez GYO'},
  {'symbol': 'AKSA', 'name': 'Aksa Akrilik Kimya Sanayi A.Ş.'},
  {'symbol': 'AKSEN', 'name': 'Aksa Enerji Üretim A.Ş.'},
  {'symbol': 'AKSGY', 'name': 'Akiş GYO'},
  {'symbol': 'AKSUE', 'name': 'Aksu Enerji Üretim A.Ş.'},
  {'symbol': 'AKYHO', 'name': 'Akdeniz Yatırım Holding'},
  {'symbol': 'ALARK', 'name': 'Alarko Holding'},
  {'symbol': 'ALBRK', 'name': 'Albaraka Türk'},
  {'symbol': 'ALBTN', 'name': 'Albayrak Hazır Beton'},
  {'symbol': 'ALCAR', 'name': 'Alarko Carrier Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'ALCTL', 'name': 'Alcatel Lucent'},
  {'symbol': 'ALFAS', 'name': 'Alfa Solar'},
  {'symbol': 'ALGYO', 'name': 'Alarko GYO'},
  {'symbol': 'ALKA', 'name': 'Alka Kimya'},
  {'symbol': 'ALKIM', 'name': 'Alkim Kimya'},
  {'symbol': 'ALKLC', 'name': 'Alkılıç Gıda'},
  {'symbol': 'ALNTF', 'name': 'Alıntı Finans'},
  {'symbol': 'ALTNY', 'name': 'Altınyıldız Mensucat'},
  {'symbol': 'ALVES', 'name': 'Alves Kablo Sanayi'},
  {'symbol': 'ANACM', 'name': 'Anadolu Cam'},
  {'symbol': 'ANELE', 'name': 'Anel Elektrik Proje'},
  {'symbol': 'ANGEN', 'name': 'Anatolia Tanı ve Biyoteknik'},
  {'symbol': 'ANHYT', 'name': 'Anadolu Hayat Emeklilik'},
  {'symbol': 'ANSGR', 'name': 'Anadolu Anonim Türk Sigorta'},
  {'symbol': 'APBDL', 'name': 'Ak Portföy BIST Banka Dışı Likit 10 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'APGLD', 'name': 'Ak Portföy Altın Katılım Borsa Yatırım Fonu'},
  {'symbol': 'APLIB', 'name': 'Ak Portföy BIST Likit Banka Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'APMDL', 'name': 'Ak Portföy BIST 100 Endeksi Model Portföy Hisse Senedi Yoğun BYF'},
  {'symbol': 'APX30', 'name': 'Ak Portföy BIST 30 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'ARASE', 'name': 'Doğu Aras Enerji'},
  {'symbol': 'ARCLK', 'name': 'Arçelik'},
  {'symbol': 'ARDYZ', 'name': 'Ard Grup Bilişim Teknolojileri'},
  {'symbol': 'ARENA', 'name': 'Arena Bilgisayar'},
  {'symbol': 'ARFYE', 'name': 'Arf Bio Yenilenebilir Enerji'},
  {'symbol': 'ARMGD', 'name': 'Armada Gıda Ticaret ve Sanayi A.Ş.'},
  {'symbol': 'ARMDA', 'name': 'Arma Dış Ticaret'},
  {'symbol': 'ARMYO', 'name': 'Arma GYO'},
  {'symbol': 'ARSEL', 'name': 'Arsel GYO'},
  {'symbol': 'ARSUZ', 'name': 'Arsuz Gıda'},
  {'symbol': 'ARTIY', 'name': 'Artı Yatırım Holding A.Ş.'},
  {'symbol': 'ARZUM', 'name': 'Arzum Elektrikli Ev Aletleri'},
  {'symbol': 'ARSAN', 'name': 'Arsan Tekstil'},
  {'symbol': 'ARTMS', 'name': 'Artemis Halı A.Ş.'},
  {'symbol': 'ASBTR', 'name': 'Aselsan Bilişim Teknolojileri A.Ş.'},
  {'symbol': 'ASELS', 'name': 'Aselsan Elektronik Sanayi'},
  {'symbol': 'ASGYO', 'name': 'Asce GYO'},
  {'symbol': 'ASTOR', 'name': 'Astor Enerji'},
  {'symbol': 'ASUZU', 'name': 'Anadolu Isuzu'},
  {'symbol': 'ATAGY', 'name': 'Ata GYO'},
  {'symbol': 'ATAKP', 'name': 'Atakey Patates Gida Sanayi'},
  {'symbol': 'ATATP', 'name': 'Atp Yazılım ve Teknoloji'},
  {'symbol': 'ATATR', 'name': 'Ata Turizm'},
  {'symbol': 'ATEKS', 'name': 'Akın Tekstil'},
  {'symbol': 'ATLAS', 'name': 'Atlas Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'ATSYH', 'name': 'Atlantis Yatırım Holding A.Ş.'},
  {'symbol': 'AVGYO', 'name': 'Avrasya GYO'},
  {'symbol': 'AVHOL', 'name': 'Avrasya Holding'},
  {'symbol': 'AVOD', 'name': 'A.V.O.D Kurutulmuş Gıda'},
  {'symbol': 'AVPGY', 'name': 'Avicenna GYO'},
  {'symbol': 'AVTUR', 'name': 'Avrasya Petrol ve Turistik Tesisler Yatırımlar A.Ş.'},
  {'symbol': 'AYCES', 'name': 'Altınyunus Çeşme'},
  {'symbol': 'AYDEM', 'name': 'Aydem Enerji'},
  {'symbol': 'AYEN', 'name': 'Ayen Enerji A.Ş.'},
  {'symbol': 'AYES', 'name': 'Ayes Çelik Hasır ve Çit Sanayi A.Ş.'},
  {'symbol': 'AYGAZ', 'name': 'Aygaz A.Ş.'},
  {'symbol': 'AZTEK', 'name': 'Aztek Teknoloji Ürünleri Ticaret A.Ş.'},
  {'symbol': 'BAGFS', 'name': 'Bagfaş Bandırma Gübre'},
  {'symbol': 'BAHKM', 'name': 'Bahadır Kimya Sanayi ve Ticaret'},
  {'symbol': 'BAKAB', 'name': 'Bak Ambalaj Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BALAT', 'name': 'Balatacılar Balatacılık Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BALSU', 'name': 'Balsu Gıda'},
  {'symbol': 'BANVT', 'name': 'Banvit Bandırma Vitaminli Yem Sanayi'},
  {'symbol': 'BARMA', 'name': 'Barem Ambalaj Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BASCM', 'name': 'Baştaş Başkent Çimento Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BASGZ', 'name': 'Başkent Doğalgaz GYO'},
  {'symbol': 'BAYRK', 'name': 'Bayrak'},
  {'symbol': 'BEGYO', 'name': 'Bati Ege GYO'},
  {'symbol': 'BERA', 'name': 'Bera Holding'},
  {'symbol': 'BESLR', 'name': 'Besler Gıda ve Kimya Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BESTE', 'name': 'Best Brands Grup Enerji'},
  {'symbol': 'BETAE', 'name': 'Beta Enerji ve Teknoloji A.Ş.'},
  {'symbol': 'BEWEN', 'name': 'Bewen Enerji'},
  {'symbol': 'BEYAZ', 'name': 'Beyaz Filo Oto Kiralama'},
  {'symbol': 'BFREN', 'name': 'Bosch Fren Sistemleri Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BIENY', 'name': 'Bien Yapı Ürünleri'},
  {'symbol': 'BIGCH', 'name': 'Büyük Şefler Gıda Turizm Tekstil Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BIGEN', 'name': 'Birleşim Grup Enerji Yatırımları A.Ş.'},
  {'symbol': 'BIGTK', 'name': 'Big Medya & Teknoloji A.Ş.'},
  {'symbol': 'BIMAS', 'name': 'BİM Mağazalar'},
  {'symbol': 'BINBN', 'name': 'Bin Ulaşım ve Akıllı Şehir Teknolojileri A.Ş.'},
  {'symbol': 'BINHO', 'name': '1000 Yatırımlar Holding A.Ş.'},
  {'symbol': 'BIOEN', 'name': 'Biotrend Çevre ve Enerji Yatırımları A.Ş.'},
  {'symbol': 'BIZIM', 'name': 'Bizim Toptan Satış Mağazaları A.Ş.'},
  {'symbol': 'BJKAS', 'name': 'Beşiktaş Futbol Yatırımları'},
  {'symbol': 'BLCYT', 'name': 'Bilici Yatırım'},
  {'symbol': 'BLUME', 'name': 'Blume Metal Kimya A.Ş.'},
  {'symbol': 'BMSCH', 'name': 'BMS Çelik Hasır Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BMSTL', 'name': 'BMS Birleşik Metal Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BNTAS', 'name': 'Bantaş Bandırma Ambalaj Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BOBET', 'name': 'Boğaziçi Beton'},
  {'symbol': 'BORLS', 'name': 'Borlease Otomotiv A.Ş.'},
  {'symbol': 'BORSK', 'name': 'Bor Şeker A.Ş.'},
  {'symbol': 'BOSSA', 'name': 'Bossa Ticaret'},
  {'symbol': 'BRISA', 'name': 'Brisa Bridgestone'},
  {'symbol': 'BRKSN', 'name': 'Berkosan Yalıtım ve Tecrit Maddeleri Üretim ve Ticaret A.Ş.'},
  {'symbol': 'BRKVY', 'name': 'Birikim Varlık Yönetim A.Ş.'},
  {'symbol': 'BRLSM', 'name': 'Birleşim Mühendislik'},
  {'symbol': 'BRMEN', 'name': 'Birlik Mensucat Ticaret ve Sanayi İşletmesi A.Ş.'},
  {'symbol': 'BRSAN', 'name': 'Borusan Birleşik Boru Fabrikaları Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BRYAT', 'name': 'Borusan Yatırım ve Pazarlama A.Ş.'},
  {'symbol': 'BSOKE', 'name': 'Batı Söke Çimento'},
  {'symbol': 'BTCIM', 'name': 'Batıçim Batı Anadolu'},
  {'symbol': 'BUCIM', 'name': 'Bursa Çimento'},
  {'symbol': 'BULGS', 'name': 'Bulls Girişim Sermayesi Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'BURCE', 'name': 'Burçelik Bursa Çelik Döküm Sanayii A.Ş.'},
  {'symbol': 'BURVA', 'name': 'Burçelik Vana Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BVSAN', 'name': 'Bülbüloğlu Vinç Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BYDNR', 'name': 'Baydöner Restoranları A.Ş.'},
  {'symbol': 'CANTE', 'name': 'Çan2 Termik A.Ş.'},
  {'symbol': 'CASA', 'name': 'Casa Emtia Petrol Kimyevi ve Türevleri Sanayi Ticaret A.Ş.'},
  {'symbol': 'CATES', 'name': 'Çates Elektrik Üretim A.Ş.'},
  {'symbol': 'CCOLA', 'name': 'Coca-Cola İçecek'},
  {'symbol': 'CELHA', 'name': 'Çelik Halat ve Tel Sanayi'},
  {'symbol': 'CEMAS', 'name': 'Cemaş Döküm Sanayi A.Ş.'},
  {'symbol': 'CEMTS', 'name': 'Çemtaş Çelik Makina Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'CEMZY', 'name': 'Çem Zeytin Anonim Şirketi'},
  {'symbol': 'CEOEM', 'name': 'CEO Event Medya A.Ş.'},
  {'symbol': 'CGCAM', 'name': 'Çağdaş Cam Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'CIMSA', 'name': 'Çimsa Çimento'},
  {'symbol': 'CLEBI', 'name': 'Çelebi Hava Hizmetleri'},
  {'symbol': 'CMBTN', 'name': 'Çimbeton Hazırbeton'},
  {'symbol': 'CMENT', 'name': 'Çimentaş İzmir Çimento Fabrikası T.A.Ş.'},
  {'symbol': 'CONSE', 'name': 'Consus Enerji'},
  {'symbol': 'COSMO', 'name': 'Cosmos Yatırım Holding A.Ş.'},
  {'symbol': 'CRDFA', 'name': 'Creditwest Faktoring A.Ş.'},
  {'symbol': 'CRFSA', 'name': 'Carrefoursa'},
  {'symbol': 'CUSAN', 'name': 'Çuhadaroğlu Metal Sanayi ve Pazarlama A.Ş.'},
  {'symbol': 'CVKMD', 'name': 'CVK Madencilik'},
  {'symbol': 'CWENE', 'name': 'CW Enerji'},
  {'symbol': 'DAGI', 'name': 'Dagi Giyim'},
  {'symbol': 'DAPGM', 'name': 'DAP Gayrimenkul'},
  {'symbol': 'DARDL', 'name': 'Dardanel Önentaş'},
  {'symbol': 'DCTTR', 'name': 'DCT Trading Dış Ticaret A.Ş.'},
  {'symbol': 'DENGE', 'name': 'Denge Holding'},
  {'symbol': 'DERHL', 'name': 'Derlüks Yatırım Holding'},
  {'symbol': 'DERIM', 'name': 'Derimod Konfeksiyon Ayakkabı Deri Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'DESA', 'name': 'Desa Deri'},
  {'symbol': 'DESPC', 'name': 'Despec Bilgisayar Pazarlama ve Ticaret A.Ş.'},
  {'symbol': 'DEVA', 'name': 'Deva Holding'},
  {'symbol': 'DGATE', 'name': 'Datagate Bilgisayar'},
  {'symbol': 'DGGYO', 'name': 'Doğuş Gayrimenkul Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'DGNMO', 'name': 'Doğanlar Mobilya Grubu'},
  {'symbol': 'DIRIT', 'name': 'Diriteks Diriliş Tekstil Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'DITAS', 'name': 'Ditaş Doğan Yedek Parça'},
  {'symbol': 'DMRGD', 'name': 'Demir Unlu Mamuller Uretim'},
  {'symbol': 'DMSAS', 'name': 'Demisaş Döküm Emaye'},
  {'symbol': 'DNISI', 'name': 'Diamik Isı Makina Yalıtım'},
  {'symbol': 'DOAS', 'name': 'Doğuş Otomotiv'},
  {'symbol': 'DOCO', 'name': 'DO & CO Aktiengesellschaft'},
  {'symbol': 'DOFER', 'name': 'Dofer Yapı Malzemeleri Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'DOFRB', 'name': 'DOF Robotik Sanayi A.Ş.'},
  {'symbol': 'DOGUB', 'name': 'Doğuşan Boru Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'DOHOL', 'name': 'Doğan Şirketler Grubu'},
  {'symbol': 'DOKTA', 'name': 'Döktaş Dökümcülük Ticaret ve Sanayi A.Ş.'},
  {'symbol': 'DSTKF', 'name': 'Destek Faktoring A.Ş.'},
  {'symbol': 'DUNYH', 'name': 'Dünya Holding'},
  {'symbol': 'DURDO', 'name': 'Duran Doğan Basım ve Ambalaj'},
  {'symbol': 'DURKN', 'name': 'Durukan Şekerleme Sanayi'},
  {'symbol': 'DYOBY', 'name': 'DYO Boya Fabrikaları'},
  {'symbol': 'DZGYO', 'name': 'Deniz GYO'},
  {'symbol': 'EBEBK', 'name': 'Ebebek Mağazacılık'},
  {'symbol': 'ECILC', 'name': 'Eis Eczacıbaşı İlaç Sinai'},
  {'symbol': 'ECOGR', 'name': 'Ecogreen Enerji Holding'},
  {'symbol': 'ECZYT', 'name': 'Eczacıbaşı Yatırım'},
  {'symbol': 'EDATA', 'name': 'E-Data Teknoloji'},
  {'symbol': 'EDIP', 'name': 'Edip GYO'},
  {'symbol': 'EFOR', 'name': 'Efor Yatırım Sanayi'},
  {'symbol': 'EGEEN', 'name': 'Ege Endüstri ve Tic.'},
  {'symbol': 'EGEGY', 'name': 'Egeyapı Avrupa Gayrimenkul Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'EGEPO', 'name': 'Nasmed Özel Sağlık Hizmetleri Ticaret A.Ş.'},
  {'symbol': 'EGGUB', 'name': 'Ege Gübre Sanayi'},
  {'symbol': 'EGPRO', 'name': 'Ege Profil Ticaret ve Sanayi A.Ş.'},
  {'symbol': 'EGSER', 'name': 'Ege Seramik Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'EKDMR', 'name': 'Ekinciler Demir ve Çelik Sanayi'},
  {'symbol': 'EKGYO', 'name': 'Emlak Konut GYO'},
  {'symbol': 'EKIM', 'name': 'Ekim Turizm Tic.'},
  {'symbol': 'EKIZ', 'name': 'Ekiz Kimya Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'EKOS', 'name': 'Ekos Teknoloji ve Elektirik'},
  {'symbol': 'EKSUN', 'name': 'Eksun Gıda'},
  {'symbol': 'ELITE', 'name': 'Elite Naturel Organik Gıda'},
  {'symbol': 'EMKEL', 'name': 'Emek Elektrik Endüstrisi'},
  {'symbol': 'EMNIS', 'name': 'Eminiş Ambalaj Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'EMPAE', 'name': 'Empae Elektronik Sanayi'},
  {'symbol': 'ENDAE', 'name': 'Enda Enerji Holding'},
  {'symbol': 'ENERY', 'name': 'Enerya Enerji A.Ş.'},
  {'symbol': 'ENJSA', 'name': 'Enerjisa Enerji A.Ş.'},
  {'symbol': 'ENKAI', 'name': 'Enka İnşaat ve Sanayi'},
  {'symbol': 'ENPRA', 'name': 'Enpara Bank A.Ş.'},
  {'symbol': 'ENSRI', 'name': 'Ensari Deri Gıda Sanayi'},
  {'symbol': 'ENTRA', 'name': 'IC Entrra Yenilebilir Enerji'},
  {'symbol': 'EPLAS', 'name': 'Egeplast Ege Plastik'},
  {'symbol': 'ERBOS', 'name': 'Erbosan Erciyas Boru Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'ERCB', 'name': 'Erciyas Çelik Boru Sanayi'},
  {'symbol': 'EREGL', 'name': 'Ereğli Demir Çelik'},
  {'symbol': 'ERSU', 'name': 'Ersu Meyve ve Gıda Sanayi A.Ş.'},
  {'symbol': 'ESCAR', 'name': 'Escar Filo Kiralama Hizmetleri A.Ş.'},
  {'symbol': 'ESCOM', 'name': 'Escort Teknoloji Yatırım A.Ş.'},
  {'symbol': 'ESEN', 'name': 'Esenboğa Elektirik Üretim A.Ş.'},
  {'symbol': 'ETILR', 'name': 'Etiler  ve Tic. A.Ş.'},
  {'symbol': 'ETYAT', 'name': 'Euro Trend Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'EUHOL', 'name': 'Euro Yatırım Holding A.Ş.'},
  {'symbol': 'EUKYO', 'name': 'Euro Kapital Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'EUPWR', 'name': 'EuroPower Enerji'},
  {'symbol': 'EUREN', 'name': 'Europen Endüstri İnşaat'},
  {'symbol': 'EUYO', 'name': 'Euro Menkul Kıymet Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'EYGYO', 'name': 'Eyg GYO'},
  {'symbol': 'FADE', 'name': 'Fade Gıda Yatırım Sanayi'},
  {'symbol': 'FENER', 'name': 'Fenerbahçe Futbol A.Ş.'},
  {'symbol': 'FLAP', 'name': 'Flap Kongre Toplantı Hizmetleri Otomotiv ve Turizm A.Ş.'},
  {'symbol': 'FMIZP', 'name': 'Federal-Mogul İzmit Piston'},
  {'symbol': 'FONET', 'name': 'Fonet Bilgi Teknolojileri'},
  {'symbol': 'FORMT', 'name': 'Formet Metal ve Cam Sanayi'},
  {'symbol': 'FORTE', 'name': 'Forte Bilgi İletişim'},
  {'symbol': 'FRIGO', 'name': 'Frigo-Pak Gıda'},
  {'symbol': 'FRMPL', 'name': 'Formul Plastik ve Metal Sanayi'},
  {'symbol': 'FROTO', 'name': 'Ford Otomotiv Sanayi A.Ş.'},
  {'symbol': 'FZLGY', 'name': 'Fuzul GYO'},
  {'symbol': 'GARAN', 'name': 'Türkiye Garanti Bankası A.Ş.'},
  {'symbol': 'GARFA', 'name': 'Garanti Faktoring'},
  {'symbol': 'GATEG', 'name': 'Gate Group Teknoloji Medya ve Siber Güv. A.Ş.'},
  {'symbol': 'GEDIK', 'name': 'Gedik Yatırım'},
  {'symbol': 'GEDZA', 'name': 'Gediz Ambalaj Sanayi'},
  {'symbol': 'GENIL', 'name': 'Gen İlaç ve Sağlık Ürünleri'},
  {'symbol': 'GENKM', 'name': 'Gentaş Kimya Sanayi'},
  {'symbol': 'GENTS', 'name': 'Gentaş Dekoratif Yüzeyler'},
  {'symbol': 'GEREL', 'name': 'Gersan Elektrik Tic.'},
  {'symbol': 'GESAN', 'name': 'Girişim Elektirik Sanayi'},
  {'symbol': 'GIPTA', 'name': 'Gipta Ofis Kırtasiye ve Promosyon'},
  {'symbol': 'GLBMD', 'name': 'Global Menkul Değerler A.Ş.'},
  {'symbol': 'GLCVY', 'name': 'Gelecek Varlık Yönetimi A.Ş.'},
  {'symbol': 'GLDTR', 'name': 'QNB Portföy Altın Borsa Yatırım Fonu'},
  {'symbol': 'GLRMK', 'name': 'Gülermak Ağır Sanayi İnşaat ve Taahhüt A.Ş.'},
  {'symbol': 'GLRYH', 'name': 'Güler Yatırım Holding'},
  {'symbol': 'GLYHO', 'name': 'Global Yatırım Holding'},
  {'symbol': 'GMSTR', 'name': 'QNB Portföy Gümüş Borsa Yatırım Fonu'},
  {'symbol': 'GMTAS', 'name': 'Gimat Mağazacılık Sanayi'},
  {'symbol': 'GOKNR', 'name': 'Göknur Gıda Maddeleri'},
  {'symbol': 'GOLDA', 'name': 'Golda Gıda Sanayi ve Tic.'},
  {'symbol': 'GOLTS', 'name': 'Göltas Göller Bölgesi Çimento'},
  {'symbol': 'GOODY', 'name': 'Goodyear Lastikleri A.Ş.'},
  {'symbol': 'GOZDE', 'name': 'Gözde Girişim Sermayesi'},
  {'symbol': 'GRNYO', 'name': 'Garanti Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'GRSEL', 'name': 'Gur-Sel Turizm'},
  {'symbol': 'GRTHO', 'name': 'Grainturk Holding A.Ş.'},
  {'symbol': 'GSDDE', 'name': 'GSD Denizcilik Gayrimenkul İnşaat San. Tic. A.Ş.'},
  {'symbol': 'GSDHO', 'name': 'GSD Holding A.Ş.'},
  {'symbol': 'GSRAY', 'name': 'Galatasaray Sportif'},
  {'symbol': 'GUBRF', 'name': 'Gübre Fabrikaları T.A.Ş.'},
  {'symbol': 'GUNDG', 'name': 'Gündoğdu Gıda Sut Ürünleri'},
  {'symbol': 'GWIND', 'name': 'Galata Wind Enerji A.Ş.'},
  {'symbol': 'GZNMI', 'name': 'Gezinomi Seyehat Turizm A.Ş.'},
  {'symbol': 'HALKB', 'name': 'Türkiye Halk Bankası A.Ş.'},
  {'symbol': 'HALKS', 'name': 'Halkbank Kısa Vadeli Kira Sertifikası Katılım Fonu'},
  {'symbol': 'HATEK', 'name': 'Hateks Hatay Tekstil İşletmesi'},
  {'symbol': 'HATSN', 'name': 'Hat-San Gemi İnşaat Bakım Onarım A.Ş.'},
  {'symbol': 'HDFGS', 'name': 'Hedef Girişim Sermayesi YO A.Ş.'},
  {'symbol': 'HEDEF', 'name': 'Hedef Holding A.Ş.'},
  {'symbol': 'HEKTS', 'name': 'Hektaş Ticaret T.A.Ş.'},
  {'symbol': 'HKTM', 'name': 'Hidropar Hareket Kontrol Teknolojileri'},
  {'symbol': 'HLGYO', 'name': 'Halk GYO'},
  {'symbol': 'HOROZ', 'name': 'Horoz Lojistik Kargo Hizmetleri'},
  {'symbol': 'HRKET', 'name': 'Hareket Proje Taşımacılığı ve Yük Mühendisliği A.Ş.'},
  {'symbol': 'HTTBT', 'name': 'Hitit Bilgisayar Hizmetleri'},
  {'symbol': 'HUBVC', 'name': 'Hub Girişim Sermayesi Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'HUNER', 'name': 'Hün Yenilenebilir Enerji'},
  {'symbol': 'HURGZ', 'name': 'Hürriyet Gazetecilik'},
  {'symbol': 'ICBCT', 'name': 'ICBC Turkey Bank A.Ş.'},
  {'symbol': 'ICUGS', 'name': 'ICU Girişim Sermayesi Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'IDGYO', 'name': 'İdealist Gayrimenkul Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'IEYHO', 'name': 'Işıklar Enerji ve Yapı Holding A.Ş.'},
  {'symbol': 'IHAAS', 'name': 'İhlas Haber Ajansı A.Ş.'},
  {'symbol': 'IHEVA', 'name': 'İhlas Ev Aletleri İmalat Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'IHGZT', 'name': 'İhlas Gazetecilik A.Ş.'},
  {'symbol': 'IHLAS', 'name': 'İhlas Holding A.Ş.'},
  {'symbol': 'IHLGM', 'name': 'İhlas Gayrimenkul Proje Tic. A.Ş.'},
  {'symbol': 'IHYAY', 'name': 'İhlas Yayın Holding A.Ş.'},
  {'symbol': 'IMASM', 'name': 'İmaş Makina Sanayi A.Ş.'},
  {'symbol': 'INDES', 'name': 'İndeks Bilgisayar Sistemleri A.Ş.'},
  {'symbol': 'INFO', 'name': 'İnfo Yatırım Menkul Değerler A.Ş.'},
  {'symbol': 'INGRM', 'name': 'İngram Micro Bilişim Sis. A.Ş.'},
  {'symbol': 'INTEK', 'name': 'Innosa Teknoloji A.Ş.'},
  {'symbol': 'INTEM', 'name': 'İntema Teknoloji ve Bilişim A.Ş.'},
  {'symbol': 'INVEO', 'name': 'İnveo Yatırım Holding A.Ş.'},
  {'symbol': 'INVES', 'name': 'İnvestco Holding A.Ş.'},
  {'symbol': 'ISATR', 'name': 'İş Bankası A Grubu'},
  {'symbol': 'ISBIR', 'name': 'İşbir Holding A.Ş.'},
  {'symbol': 'ISBTR', 'name': 'İş Bankası B Grubu'},
  {'symbol': 'ISCTR', 'name': 'İş Bankası C'},
  {'symbol': 'ISDMR', 'name': 'İskenderun Demir ve Çelik A.Ş.'},
  {'symbol': 'ISFIN', 'name': 'İş Finansal Kiralama A.Ş.'},
  {'symbol': 'ISGLK', 'name': 'İş Girişim Sermayesi Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'ISGSY', 'name': 'İş Girişim Sermayesi'},
  {'symbol': 'ISGYO', 'name': 'İş GYO'},
  {'symbol': 'ISKPL', 'name': 'Işık Plastik Sanayi ve Dış Tic. A.Ş.'},
  {'symbol': 'ISMEN', 'name': 'İş Yatırım Menkul Değerler'},
  {'symbol': 'ISSEN', 'name': 'İşbir Sentetik Dokuma Sanayi A.Ş.'},
  {'symbol': 'ISVEA', 'name': 'İsvea Seramik ve Banyo Ürünleri'},
  {'symbol': 'ISYAT', 'name': 'İş Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'IZENR', 'name': 'İzdemir Enerji Elektirk Üretim A.Ş.'},
  {'symbol': 'IZFAS', 'name': 'İzmir Fırça Sanayi ve Tic. A.Ş.'},
  {'symbol': 'IZINV', 'name': 'İz Yatırım Holding A.Ş.'},
  {'symbol': 'IZMDC', 'name': 'İzmir Demir Çelik Sanayi A.Ş.'},
  {'symbol': 'JANTS', 'name': 'Jantsa Jant Sanayi A.Ş.'},
  {'symbol': 'KAPLM', 'name': 'Kaplamin Ambalaj Sanayi ve Tic. A.Ş.'},
  {'symbol': 'KARCL', 'name': 'Kardemir Çelik Sanayi A.Ş.'},
  {'symbol': 'KAREL', 'name': 'Karel Elektronik Sanayi ve Tic. A.Ş.'},
  {'symbol': 'KARSN', 'name': 'Karsan Otomotiv Sanayi'},
  {'symbol': 'KARTN', 'name': 'Kartonsan Karton Sanayi'},
  {'symbol': 'KATMR', 'name': 'Katmerciler Araç Üstü Ekipman'},
  {'symbol': 'KAYSE', 'name': 'Kayseri Şeker Fabrikası A.Ş.'},
  {'symbol': 'KBORU', 'name': 'Kuzey Boru A.Ş.'},
  {'symbol': 'KCAER', 'name': 'Kocaer Çelik Sanayi ve Tic. A.Ş. Enerji'},
  {'symbol': 'KCHOL', 'name': 'Koç Holding A.Ş.'},
  {'symbol': 'KENT', 'name': 'Kent Gıda Maddeleri Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'KERVN', 'name': 'Kervansaray Yatırım Holding A.Ş.'},
  {'symbol': 'KFEIN', 'name': 'Kafein Yazılım Hizmetleri A.Ş.'},
  {'symbol': 'KGYO', 'name': 'Koray GYO'},
  {'symbol': 'KIMMR', 'name': 'Ersan Alışveriş Hizmetleri ve Gıda San. Tic. A.Ş.'},
  {'symbol': 'KLGYO', 'name': 'Kiler GYO'},
  {'symbol': 'KLKIM', 'name': 'Kalekim Kimyevi Maddeler ve Tic. A.Ş.'},
  {'symbol': 'KLMSN', 'name': 'Klimasan Klima San. ve Tic. A.Ş.'},
  {'symbol': 'KLNMA', 'name': 'Türkiye Kalkınma ve Yatırım Bankası A.Ş.'},
  {'symbol': 'KLRHO', 'name': 'Kiler Holding A.Ş.'},
  {'symbol': 'KLSER', 'name': 'Kaleseramik Çanakkale Kalebodur Seramik A.Ş.'},
  {'symbol': 'KLSYN', 'name': 'Koleksiyon mobilya Sanayi A.Ş.'},
  {'symbol': 'KLYPV', 'name': 'Kalyon Güneş Teknolojileri A.Ş.'},
  {'symbol': 'KMPUR', 'name': 'Kimteks Poliüretan San. Tic. A.Ş.'},
  {'symbol': 'KNFRT', 'name': 'Konfrut Gıda Sanayi ve Tic. A.Ş.'},
  {'symbol': 'KOCMT', 'name': 'Koç Metalurji A.Ş.'},
  {'symbol': 'KONKA', 'name': 'Konya Kağıt Sanayi ve Tic. A.Ş.'},
  {'symbol': 'KONTR', 'name': 'Kontrolmatik Teknoloji ve Müh. A.Ş.'},
  {'symbol': 'KONYA', 'name': 'Konya Çimento Sanayi A.Ş.'},
  {'symbol': 'KOPOL', 'name': 'Koza Polyester Sanayi ve Tic. A.Ş.'},
  {'symbol': 'KORDS', 'name': 'Kordsa Teknik Tekstil A.Ş.'},
  {'symbol': 'KOTON', 'name': 'Koton Mağazacılık Tekstil. A.Ş.'},
  {'symbol': 'KRDMA', 'name': 'Kardemir Karabük Demir Çelik Sanayi ve Ticaret A.Ş. (A)'},
  {'symbol': 'KRDMB', 'name': 'Kardemir Karabük Demir Çelik Sanayi ve Ticaret A.Ş. (B)'},
  {'symbol': 'KRDMD', 'name': 'Kardemir Karabuk Demir Çelik San. ve Tic. A.Ş.'},
  {'symbol': 'KRGYO', 'name': 'Karşıyaka GYO'},
  {'symbol': 'KRONT', 'name': 'Kron Telekomünikasyon A.Ş.'},
  {'symbol': 'KRPLS', 'name': 'Koroplast Temizlik Ambalaj San. ve Tic. A.Ş.'},
  {'symbol': 'KRSTL', 'name': 'Kristal Kola ve Meşrubat San. ve Tic. A.Ş.'},
  {'symbol': 'KRTEK', 'name': 'Karsu Tekstil Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'KRVGD', 'name': 'Kervan Gıda San. ve Tic. A.Ş.'},
  {'symbol': 'KSTUR', 'name': 'Kuştur Kuşadası Turizm Endüstrisi A.Ş.'},
  {'symbol': 'KTLEV', 'name': 'Katılımevim Tasarruf Finansal A.Ş.'},
  {'symbol': 'KTSKR', 'name': 'Kütahya Şeker Fab. A.Ş.'},
  {'symbol': 'KUTPO', 'name': 'Kütahya Porselen Sanayi A.Ş.'},
  {'symbol': 'KUVVA', 'name': 'Kuvva Gıda Ticaret ve Sanayi Yatırımları A.Ş.'},
  {'symbol': 'KUYAS', 'name': 'Kuyas Yatırım A.Ş.'},
  {'symbol': 'KZBGY', 'name': 'Kızılbük GYO'},
  {'symbol': 'KZGYO', 'name': 'Kuzugrup GYO'},
  {'symbol': 'LIDFA', 'name': 'Lider Faktoring A.Ş.'},
  {'symbol': 'LILAK', 'name': 'Lila Kağıt Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'LINK', 'name': 'Link Bilgisayar Sistemleri A.Ş.'},
  {'symbol': 'LKMNH', 'name': 'Lokman Hekim Engürüsağ Sağlık A.Ş.'},
  {'symbol': 'LMKDC', 'name': 'Limak Doğu Anadolu Çimento Sanayi'},
  {'symbol': 'LOGO', 'name': 'Logo Yazılım San. ve Tic. A.Ş.'},
  {'symbol': 'LRSHO', 'name': 'Loras Holding A.Ş.'},
  {'symbol': 'LUKSK', 'name': 'Lüks Kadife Ticaret ve Sanayi A.Ş.'},
  {'symbol': 'LXGYO', 'name': 'Lüxtera GYO'},
  {'symbol': 'LYDHO', 'name': 'Lydia Holding A.Ş.'},
  {'symbol': 'LYDYE', 'name': 'Lydia Yeşil Enerji Kaynakları A.Ş.'},
  {'symbol': 'MAALT', 'name': 'Marmaris Altınyunus Turistik Tesisler A.Ş.'},
  {'symbol': 'MACKO', 'name': 'Mackolik İnternet Hizmetleri A.Ş.'},
  {'symbol': 'MAGEN', 'name': 'Margün Enerji Üretim San. ve Tic. A.Ş.'},
  {'symbol': 'MAKIM', 'name': 'Makim Makina Teknoloji'},
  {'symbol': 'MAKTK', 'name': 'Makina Takım Endüstrisi A.Ş.'},
  {'symbol': 'MANAS', 'name': 'Manas Enerji Yönetim Sanayi ve Tic.'},
  {'symbol': 'MARBL', 'name': 'Tureks Turunc Madencilik İç ve Dış Tic.'},
  {'symbol': 'MARKA', 'name': 'Marka Yatırım'},
  {'symbol': 'MARMR', 'name': 'Marmara Holding A.Ş.'},
  {'symbol': 'MARTI', 'name': 'Martı Otel İşletmeleri A.Ş.'},
  {'symbol': 'MASFN', 'name': 'Masfen Enerji A.Ş'},
  {'symbol': 'MAVI', 'name': 'Mavi Giyim Sanayi ve Tic.'},
  {'symbol': 'MCARD', 'name': 'Metropal Kurumsal Hizmetler A.Ş.'},
  {'symbol': 'MEDTR', 'name': 'Meditera Tıbbi Malzeme San. ve Tic. A.Ş.'},
  {'symbol': 'MEGAP', 'name': 'Mega Polietilen Köpük Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'MEGMT', 'name': 'Mega Metal San. ve Tic. A.Ş.'},
  {'symbol': 'MEKAG', 'name': 'Meka Global Makine İmalat A.Ş.'},
  {'symbol': 'MEPET', 'name': 'Mepet Metro Petrol ve Tesisleri Sanayi Ticaret A.Ş.'},
  {'symbol': 'MERCN', 'name': 'Mercan Kimya Sanayi ve Tic.'},
  {'symbol': 'MERIT', 'name': 'Merit Turizm Yatırım ve İşletme A.Ş.'},
  {'symbol': 'MERKO', 'name': 'Merko Gıda San. ve Tic. A.Ş.'},
  {'symbol': 'METEN', 'name': 'Metgun Enerji Yatırımları A.Ş.'},
  {'symbol': 'METRO', 'name': 'Metro Ticari ve Mali Yatrımlar'},
  {'symbol': 'MEYSU', 'name': 'MeySu Gıda San. ve Tic. A.Ş.'},
  {'symbol': 'MGROS', 'name': 'Migros Ticaret A.Ş.'},
  {'symbol': 'MHRGY', 'name': 'Mhr GYO'},
  {'symbol': 'MIATK', 'name': 'Mia Teknoloji A.Ş.'},
  {'symbol': 'MMCAS', 'name': 'MMC Sanayi ve Ticari Yatırımlar A.Ş.'},
  {'symbol': 'MNDRS', 'name': 'Menderes Tekstil'},
  {'symbol': 'MNDTR', 'name': 'Mondi Turkey Oluklu Mukavva Kağıt A.Ş.'},
  {'symbol': 'MOBTL', 'name': 'Mobiltel İletişim Hizmetleri A.Ş.'},
  {'symbol': 'MOGAN', 'name': 'Mogan Enerji Yatırım Holding'},
  {'symbol': 'MOPAS', 'name': 'Mopas Marketçilik Gıda San.'},
  {'symbol': 'MPARK', 'name': 'MLP Sağlık Hizmetleri A.Ş.'},
  {'symbol': 'MRGYO', 'name': 'Martı GYO'},
  {'symbol': 'MRSHL', 'name': 'Marshall Boya ve Vernik Sanayi A.Ş.'},
  {'symbol': 'MSGYO', 'name': 'Mistral GYO'},
  {'symbol': 'MTRKS', 'name': 'Matrik Finansal Teknoloji'},
  {'symbol': 'MTRYO', 'name': 'Metro Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'MZHLD', 'name': 'Mazhar Zorlu Holding A.Ş.'},
  {'symbol': 'NATEN', 'name': 'Naturel Enerji'},
  {'symbol': 'NETAS', 'name': 'Netaş Telekomünikasyon'},
  {'symbol': 'NETCD', 'name': 'Netcad Yazılık A.Ş.'},
  {'symbol': 'NIBAS', 'name': 'Nigbaş Niğde Beton Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'NPTLR', 'name': 'Netaş Pay Rüçhan Hakkı'},
  {'symbol': 'NTGAZ', 'name': 'Naturelgaz Sanayi ve Tic.'},
  {'symbol': 'NTHOL', 'name': 'Net Holding A.Ş.'},
  {'symbol': 'NUGYO', 'name': 'Nurol GYO'},
  {'symbol': 'NUHCM', 'name': 'Nuh Çimento Sanayi A.Ş.'},
  {'symbol': 'OBAMS', 'name': 'Oba Makarnacılık Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'OBASE', 'name': 'Obase Bilgisayar ve Danışmanlık Hizmetleri Ticaret A.Ş.'},
  {'symbol': 'ODAS', 'name': 'Odaş Elektrik Üretim Sanayi'},
  {'symbol': 'ODINE', 'name': 'Odine Solutions Teknoloji Tic.'},
  {'symbol': 'OFSYM', 'name': 'Ofis Yem Gıda Sanayi Tic. A.Ş.'},
  {'symbol': 'ONCSM', 'name': 'Oncosem Onkolojik Sistemler Sanayi'},
  {'symbol': 'ONRYT', 'name': 'Onur Yüksek Teknoloji A.Ş.'},
  {'symbol': 'OPK30', 'name': 'Osmanlı Portföy Katılım 30 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'OPT25', 'name': 'Osmanlı Portföy BIST Temettü 25 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'OPTGY', 'name': 'Optimum Yatırım Gayrimenkul Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'OPTLR', 'name': 'Osmanlı Portföy TL Kısa Vadeli Borçlanma Araçları BYF'},
  {'symbol': 'OPX30', 'name': 'Osmanlı Portföy BIST 30 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'ORCAY', 'name': 'Orçay Ortaköy Çay Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'ORGE', 'name': 'Orge Enerji Elektirik'},
  {'symbol': 'ORMA', 'name': 'Orma Orman Mahsulleri Entegre Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'ORZAX', 'name': 'Orzaks İlaç ve Kimya Sanayi'},
  {'symbol': 'OSMEN', 'name': 'Osman Yatırım Menkul Değerler A.Ş.'},
  {'symbol': 'OSTIM', 'name': 'OSTİM Endüstriyel'},
  {'symbol': 'OTKAR', 'name': 'Otokar Otomotiv ve Sanayi'},
  {'symbol': 'OTTO', 'name': 'Otto Holding A.Ş.'},
  {'symbol': 'OYAKC', 'name': 'Oyak Çimento Fabrikaları A.Ş.'},
  {'symbol': 'OYAYO', 'name': 'Oyak Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'OYLUM', 'name': 'Oylum Sınai Yatırımlar A.Ş.'},
  {'symbol': 'OYYAT', 'name': 'Oyak Yatırım Menkul Değerler'},
  {'symbol': 'OZATD', 'name': 'Özata Denizcilik Sanayi'},
  {'symbol': 'OZGYO', 'name': 'Özderici GYO'},
  {'symbol': 'OZKGY', 'name': 'Özak GYO'},
  {'symbol': 'OZRDN', 'name': 'Özerden Plastik Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'OZSUB', 'name': 'Özsu Balık üretim A.Ş.'},
  {'symbol': 'OZYSR', 'name': 'Özyaşar Tel ve Galvanizleme San. A.Ş.'},
  {'symbol': 'PAGYO', 'name': 'Panora GYO'},
  {'symbol': 'PAHOL', 'name': 'Pasifik Holding A.Ş.'},
  {'symbol': 'PAMEL', 'name': 'Pamel Yenilenebilir Elektrik Üretim A.Ş.'},
  {'symbol': 'PAPIL', 'name': 'Papilion Savunma Teknolojileri'},
  {'symbol': 'PARSN', 'name': 'Parsan Makina Parçaları'},
  {'symbol': 'PASEU', 'name': 'Pasifik Eurasia Lojistik Dış Ticaret A.Ş.'},
  {'symbol': 'PATEK', 'name': 'Patek Teknoloji A.Ş.'},
  {'symbol': 'PCILT', 'name': 'PC İletişim ve Medya Hizmetleri'},
  {'symbol': 'PEKGY', 'name': 'Peker GYO'},
  {'symbol': 'PENGD', 'name': 'Penguen Gıda Sanayi A.Ş.'},
  {'symbol': 'PENTA', 'name': 'Penta Teknoloji Ürünleri'},
  {'symbol': 'PETKM', 'name': 'Petkim Petrokimya Holding'},
  {'symbol': 'PETUN', 'name': 'Pınar Entegre Et ve Un Sanayii A.Ş.'},
  {'symbol': 'PGSUS', 'name': 'Pegasus Hava Taşımacılığı'},
  {'symbol': 'PINSU', 'name': 'Pınar Su İçecek Sanayi'},
  {'symbol': 'PKART', 'name': 'Plastikkart Akıllı kart'},
  {'symbol': 'PKENT', 'name': 'Petrokent Turizm'},
  {'symbol': 'PLTUR', 'name': 'Platform Turizm Taşımacılık'},
  {'symbol': 'PNLSN', 'name': 'Panelsan Çatı Cephe Sistemleri Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'PNSUT', 'name': 'Pınar Süt Mamulleri'},
  {'symbol': 'POLHO', 'name': 'Polisan Holding'},
  {'symbol': 'POLTK', 'name': 'Politeknik'},
  {'symbol': 'PRDGS', 'name': 'Pardus Girişim Sermayesi'},
  {'symbol': 'PRKAB', 'name': 'Türk Prysmian Kablo ve Sis. A.Ş.'},
  {'symbol': 'PRKME', 'name': 'Park Elektirk Üretim'},
  {'symbol': 'PRZMA', 'name': 'Prizma Pres Matbaacılık Yayıncılık Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'PSDTC', 'name': 'Pergamon Status Dış Ticaret A.Ş.'},
  {'symbol': 'PSGYO', 'name': 'Pasifik GYO'},
  {'symbol': 'QNBFK', 'name': 'QNB Finans Finansal Kiralama A.Ş.'},
  {'symbol': 'QNBTR', 'name': 'QNB Bank A.Ş.'},
  {'symbol': 'QTEMZ', 'name': 'QNB Portföy Temiz Enerji Değişken BYF'},
  {'symbol': 'QUAGR', 'name': 'Qua Granite Hayal Yapı'},
  {'symbol': 'QUICK', 'name': 'Quick Sigorta A.Ş.'},
  {'symbol': 'RALYH', 'name': 'Ray Holding A.Ş.'},
  {'symbol': 'RAYSG', 'name': 'Ray Sigorta A.Ş'},
  {'symbol': 'REEDR', 'name': 'Reeder Teknoloji Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'RGYAS', 'name': 'Rönesans GYO'},
  {'symbol': 'RNPOL', 'name': 'Rainbow Polikarbonat Sanayi Ticaret A.Ş.'},
  {'symbol': 'RODRG', 'name': 'Rodrigo Tekstil Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'RTALB', 'name': 'RTA Laboratuvar Biyolojik Ürünler'},
  {'symbol': 'RUBNS', 'name': 'Rubenis Tekstik Sanayi'},
  {'symbol': 'RUZYE', 'name': 'Ruzy Madencilik ve Enerji'},
  {'symbol': 'RYGYO', 'name': 'Reysaş GYO'},
  {'symbol': 'RYSAS', 'name': 'Reysaş Taşımacılık'},
  {'symbol': 'SAFKR', 'name': 'Safkar Ege Soğutmacılık'},
  {'symbol': 'SAHOL', 'name': 'Hacı Ömer Sabancı Holding'},
  {'symbol': 'SAMAT', 'name': 'Saray Matbaacılık Kâğıtçılık Kırtasiyecilik Ticaret ve Sanayi A.Ş.'},
  {'symbol': 'SANEL', 'name': 'San-El Mühendislik Elektrik Taahhüt Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'SANFM', 'name': 'Sanifoam Endüstri'},
  {'symbol': 'SANKO', 'name': 'Sanko Pazarlama İthalat İhracat A.Ş.'},
  {'symbol': 'SARAE', 'name': 'Sa-Ra Enerji'},
  {'symbol': 'SARKY', 'name': 'Sarkuysan Elektrolitik Bakır Sanayi'},
  {'symbol': 'SASA', 'name': 'Sasa Polyester Sanayi'},
  {'symbol': 'SAYAS', 'name': 'Say Yenilenebilir Enerji Ekipmanları Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'SDTTR', 'name': 'SDT Uzay ve Savunma Teknolojileri A.Ş.'},
  {'symbol': 'SEALE', 'name': 'Seale'},
  {'symbol': 'SEGMN', 'name': 'Segmen Kardeşler Gıda Uretim ve Ambalaj Sanayi A.Ş.'},
  {'symbol': 'SEGYO', 'name': 'Seğmen GYO'},
  {'symbol': 'SEKFK', 'name': 'Şeker Finansal Kiralama A.Ş.'},
  {'symbol': 'SEKUR', 'name': 'Sekuro Plastik Ambalaj Sanayi A.Ş.'},
  {'symbol': 'SELEC', 'name': 'Selçuk Ecza Deposu Ticaret ve Sanayi A.Ş.'},
  {'symbol': 'SELVA', 'name': 'Selva Gıda Sanayi'},
  {'symbol': 'SERNT', 'name': 'Seranit Granit Seramik San.'},
  {'symbol': 'SEYKM', 'name': 'Seyitler Kimya Sanayi A.Ş.'},
  {'symbol': 'SILVR', 'name': 'Silverline Endüstri ve Ticaret A.Ş.'},
  {'symbol': 'SISE', 'name': 'Türkiye Şişe ve Cam Fabrikaları'},
  {'symbol': 'SKBNK', 'name': 'Şekerbank T.A.Ş.'},
  {'symbol': 'SKTAS', 'name': 'Söktaş Tekstil'},
  {'symbol': 'SKYLP', 'name': 'Skyalp Finansal Teknolojiler ve Danışmanlık A.Ş.'},
  {'symbol': 'SKYMD', 'name': 'Seker Yatırım Menkul Değer A.Ş.'},
  {'symbol': 'SMART', 'name': 'Smartiks Yazılık A.Ş.'},
  {'symbol': 'SMRTG', 'name': 'Smart Güneş Enerjisi Teknolojileri'},
  {'symbol': 'SMRVA', 'name': 'Sümer Varlık yönetim A.Ş. Sağlık'},
  {'symbol': 'SNGYO', 'name': 'Sinpaş GYO'},
  {'symbol': 'SNICA', 'name': 'Sanica Isı Sanayi A.Ş.'},
  {'symbol': 'SNPAM', 'name': 'Sönmez Pamuklu Sanayii A.Ş.'},
  {'symbol': 'SODA', 'name': 'Soda Sanayii'},
  {'symbol': 'SODSN', 'name': 'Sodaş Sodyum Sanayii A.Ş.'},
  {'symbol': 'SOHOE', 'name': 'Soho Giyim ve Enerji'},
  {'symbol': 'SOKE', 'name': 'Söke Değirmencilik Sanayi'},
  {'symbol': 'SOKM', 'name': 'Şok Marketler Tic.'},
  {'symbol': 'SONME', 'name': 'Sönmez Filament Sentetik İplik ve Elyaf Sanayi A.Ş.'},
  {'symbol': 'SRVGY', 'name': 'Servet GYO'},
  {'symbol': 'SSAAT', 'name': 'Saat ve Saat Sanayi ve Tic.'},
  {'symbol': 'SUMAS', 'name': 'Sumaş Suni Tahta ve Mobilya Sanayi A.Ş.'},
  {'symbol': 'SUNTK', 'name': 'Sun Tekstil Sanayi ve Tic.'},
  {'symbol': 'SURGY', 'name': 'Sur Yapı GYO'},
  {'symbol': 'SUWEN', 'name': 'Süwen İç Giyim'},
  {'symbol': 'SVGYO', 'name': 'Savur Gayrimenkul Yatirim Ortakligi A.S.'},
  {'symbol': 'TABGD', 'name': 'TAB Gıda Sanayi A.Ş.'},
  {'symbol': 'TARKM', 'name': 'Tarkim Bitki Koruma Sanayi'},
  {'symbol': 'TATEN', 'name': 'Tatlıpınar Enerji'},
  {'symbol': 'TATGD', 'name': 'Tat Gıda Sanayi A.Ş.'},
  {'symbol': 'TAVHL', 'name': 'TAV Havalimanları Holding'},
  {'symbol': 'TBORG', 'name': 'Türk Tuborg Bira ve Malt Sanayi A.Ş.'},
  {'symbol': 'TCELL', 'name': 'Turkcell İletişim Hizmetleri A.Ş.'},
  {'symbol': 'TCKRC', 'name': 'Kıraç Galvaniz Telekomünikasyon Metal Makine İnşaat Elektrik Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'TDGYO', 'name': 'Trend Gayrimenkul Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'TEHOL', 'name': 'Tera Yatırım Teknoloji Holding A.Ş.'},
  {'symbol': 'TEKTU', 'name': 'Tek-Art İnşaat Ticaret'},
  {'symbol': 'TERA', 'name': 'Tera Yatırım Menkul Değerler A.Ş.'},
  {'symbol': 'TEZOL', 'name': 'Europap Tezol Kağıt SAn.'},
  {'symbol': 'TGSAS', 'name': 'Tgs Dış Ticaret A.Ş.'},
  {'symbol': 'THYAO', 'name': 'Türk Hava Yolları'},
  {'symbol': 'TKFEN', 'name': 'Tekfen Holding A.Ş.'},
  {'symbol': 'TKNSA', 'name': 'Teknosa İç ve Dış Tic.'},
  {'symbol': 'TLMAN', 'name': 'Trabzon Liman İşletmeciliği A.Ş.'},
  {'symbol': 'TMPOL', 'name': 'Temapol Polimer Plastik ve İnşaat Sanayi Tic. A.Ş.'},
  {'symbol': 'TMSN', 'name': 'Tümosan Motor ve Traktör San. A.Ş.'},
  {'symbol': 'TNZTP', 'name': 'Tapdi Oksijen Özel Sağlık Hizmetleri A.Ş.'},
  {'symbol': 'TOASO', 'name': 'Tofaş Türk Oto. Fab.'},
  {'symbol': 'TRALT', 'name': 'Türk Altın İşletmeleri A.Ş.'},
  {'symbol': 'TRCAS', 'name': 'Turcas Petrol A.Ş.'},
  {'symbol': 'TRENJ', 'name': 'Tr Doğal Enerji Kaynakları'},
  {'symbol': 'TRGYO', 'name': 'Torunlar GYO'},
  {'symbol': 'TRHOL', 'name': 'Tera Finansal İnvestments Holding A.Ş.'},
  {'symbol': 'TRILC', 'name': 'Türk İlaç ve Serum Sanayi A.Ş.'},
  {'symbol': 'TRMET', 'name': 'TR Anadolu Metal Madencilik İşletmeleri A.Ş.'},
  {'symbol': 'TSGYO', 'name': 'TSKB Gayrimenkul Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'TSKB', 'name': 'Türkiye Sınai Kalkınma Bankası A.Ş.'},
  {'symbol': 'TSPOR', 'name': 'Trabzonspor Spoertif Yatırım A.Ş.'},
  {'symbol': 'TTKOM', 'name': 'Türk Telekomünikasyon A.Ş.'},
  {'symbol': 'TTRAK', 'name': 'Türk Traktör ve Ziraat Makineleri A.Ş.'},
  {'symbol': 'TUCLK', 'name': 'Tuğçelik Alüminyum ve Metal'},
  {'symbol': 'TUKAS', 'name': 'Tukaş Gıda Sanayi ve Tic. A.Ş.'},
  {'symbol': 'TUPRS', 'name': 'Tüpraş Türkiye Petrol Rafineleri A.Ş.'},
  {'symbol': 'TUREX', 'name': 'Tureks Turizm Taşımacılık A.Ş.'},
  {'symbol': 'TURGG', 'name': 'Türker Proje Gayrimenkul ve Yatırım A.Ş.'},
  {'symbol': 'TURSG', 'name': 'Türkiye Sigorta A.Ş.'},
  {'symbol': 'UCAYM', 'name': 'Üçay Mühendislik Enerji ve İklimlendirme Teknolojileri A.Ş.'},
  {'symbol': 'UFUK', 'name': 'Ufuk Yatırım Yönetim ve Gayrimenkul A.Ş.'},
  {'symbol': 'ULAS', 'name': 'Ulaşlar Turizm Yatırımları ve Dayanıklı Tüketim Malları Ticaret A.Ş.'},
  {'symbol': 'ULKER', 'name': 'Ülker Bisküvi Sanayi A.Ş.'},
  {'symbol': 'ULUFA', 'name': 'Ulusoy Faktoring A.Ş.'},
  {'symbol': 'ULUSE', 'name': 'Ulusoy Elektrik İmalat Tahhüt ve Tic. A.Ş.'},
  {'symbol': 'ULUUN', 'name': 'Ulusoy Un Sanayi ve Tic. A.Ş.'},
  {'symbol': 'UNLU', 'name': 'Ünlü Yatırım Holding A.Ş.'},
  {'symbol': 'USAK', 'name': 'Uşak Seramik Sanayi A.Ş.'},
  {'symbol': 'USDTR', 'name': 'QNB Portföy Dolar Borsa Yatırım Fonu'},
  {'symbol': 'VAKBN', 'name': 'Türkiye Vakıflar Bankası T.A.O.'},
  {'symbol': 'VAKFA', 'name': 'Vakıf Faktoring A.Ş.'},
  {'symbol': 'VAKFN', 'name': 'Vakıf Finansal Kiralama A.Ş.'},
  {'symbol': 'VAKKO', 'name': 'Vakko Tekstil ve Hazır Giyim Sanayi'},
  {'symbol': 'VANGD', 'name': 'Vanet Gıda Sanayi İç ve Dış Ticaret A.Ş.'},
  {'symbol': 'VBTYZ', 'name': 'Vbt Yazılım A.Ş.'},
  {'symbol': 'VERTU', 'name': 'Vertu'},
  {'symbol': 'VERUS', 'name': 'Verus'},
  {'symbol': 'VESBE', 'name': 'Vestel Beyaz Eşya Sanayi'},
  {'symbol': 'VESTL', 'name': 'Vestel Elektronik Sanayi'},
  {'symbol': 'VKFYO', 'name': 'Vakıf Menkul Kıymet Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'VKGYO', 'name': 'Vakıf GYO'},
  {'symbol': 'VKING', 'name': 'Viking Kağıt ve Selüloz A.Ş.'},
  {'symbol': 'VRGYO', 'name': 'Vera Konsept GYO'},
  {'symbol': 'VSNMD', 'name': 'Vişne Madencilik Üretim Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'X030S', 'name': 'X030S'},
  {'symbol': 'X100S', 'name': 'X100S'},
  {'symbol': 'XBANA', 'name': 'XBANA'},
  {'symbol': 'XBANK', 'name': 'XBANK'},
  {'symbol': 'XBLSM', 'name': 'XBLSM'},
  {'symbol': 'XELKT', 'name': 'XELKT'},
  {'symbol': 'XFINK', 'name': 'XFINK'},
  {'symbol': 'XGIDA', 'name': 'XGIDA'},
  {'symbol': 'XGMYO', 'name': 'XGMYO'},
  {'symbol': 'XHARZ', 'name': 'XHARZ'},
  {'symbol': 'XHOLD', 'name': 'XHOLD'},
  {'symbol': 'XILTM', 'name': 'XILTM'},
  {'symbol': 'XINSA', 'name': 'XINSA'},
  {'symbol': 'XKAGT', 'name': 'XKAGT'},
  {'symbol': 'XKMYA', 'name': 'XKMYA'},
  {'symbol': 'XKOBI', 'name': 'XKOBI'},
  {'symbol': 'XKURY', 'name': 'XKURY'},
  {'symbol': 'XMADN', 'name': 'XMADN'},
  {'symbol': 'XMANA', 'name': 'XMANA'},
  {'symbol': 'XMESY', 'name': 'XMESY'},
  {'symbol': 'XSADA', 'name': 'XSADA'},
  {'symbol': 'XSANK', 'name': 'XSANK'},
  {'symbol': 'XSANT', 'name': 'XSANT'},
  {'symbol': 'XSBAL', 'name': 'XSBAL'},
  {'symbol': 'XSBUR', 'name': 'XSBUR'},
  {'symbol': 'XSDNZ', 'name': 'XSDNZ'},
  {'symbol': 'XSGRT', 'name': 'XSGRT'},
  {'symbol': 'XSIST', 'name': 'XSIST'},
  {'symbol': 'XSIZM', 'name': 'XSIZM'},
  {'symbol': 'XSKAY', 'name': 'XSKAY'},
  {'symbol': 'XSKOC', 'name': 'XSKOC'},
  {'symbol': 'XSKON', 'name': 'XSKON'},
  {'symbol': 'XSPOR', 'name': 'XSPOR'},
  {'symbol': 'XSTKR', 'name': 'XSTKR'},
  {'symbol': 'XTAST', 'name': 'XTAST'},
  {'symbol': 'XTCRT', 'name': 'XTCRT'},
  {'symbol': 'XTEKS', 'name': 'XTEKS'},
  {'symbol': 'XTM25', 'name': 'XTM25'},
  {'symbol': 'XTMTU', 'name': 'XTMTU'},
  {'symbol': 'XTRZM', 'name': 'XTRZM'},
  {'symbol': 'XTUMY', 'name': 'XTUMY'},
  {'symbol': 'XU030', 'name': 'XU030'},
  {'symbol': 'XU050', 'name': 'XU050'},
  {'symbol': 'XU100', 'name': 'XU100'},
  {'symbol': 'XUHIZ', 'name': 'XUHIZ'},
  {'symbol': 'XULAS', 'name': 'XULAS'},
  {'symbol': 'XUMAL', 'name': 'XUMAL'},
  {'symbol': 'XUSIN', 'name': 'XUSIN'},
  {'symbol': 'XUSRD', 'name': 'XUSRD'},
  {'symbol': 'XUTEK', 'name': 'XUTEK'},
  {'symbol': 'XUTUM', 'name': 'XUTUM'},
  {'symbol': 'XYLDZ', 'name': 'XYLDZ'},
  {'symbol': 'XYORT', 'name': 'XYORT'},
  {'symbol': 'XYUZO', 'name': 'XYUZO'},
  {'symbol': 'YAPRK', 'name': 'Yaprak Süt ve Besi Çiftlikleri Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'YATAS', 'name': 'Yataş Yatak ve Yorgan Sanayi'},
  {'symbol': 'YAYLA', 'name': 'Yayla Enerji Üretim Turizm ve İnş. Tic.'},
  {'symbol': 'YBTAS', 'name': 'Yibitaş Yozgat İşçi Birliği İnşaat Malzemeleri Ticaret ve Sanayi A.Ş.'},
  {'symbol': 'YEOTK', 'name': 'YEO Teknoloji Enerji ve Endüstri A.Ş.'},
  {'symbol': 'YESIL', 'name': 'Yeşil Yatırım Holding A.Ş.'},
  {'symbol': 'YGGYO', 'name': 'Yeni Gimat GYO'},
  {'symbol': 'YIGIT', 'name': 'Yiğit Akü Malzemeleri Nakliyat Turizm Tic.'},
  {'symbol': 'YKBNK', 'name': 'Yapı ve Kredi Bankası A.Ş.'},
  {'symbol': 'YKSLN', 'name': 'Yükselen Çelik A.Ş.'},
  {'symbol': 'YONGA', 'name': 'Yonga Mobilya Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'YUNSA', 'name': 'Yünsa Yünlü Sanayi ve Tic. A.Ş.'},
  {'symbol': 'YYAPI', 'name': 'Yeşil Yapı Endüstrisi A.Ş.'},
  {'symbol': 'YYLGD', 'name': 'Yayla Agro Gıda Sanayi ve Ti. A.Ş.'},
  {'symbol': 'Z30EA', 'name': 'Ziraat Portföy BIST 30 Eşit Ağırlıklı Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'Z30KE', 'name': 'Ziraat Portföy Katılım 30 Eşit Ağırlıklı Hisse Senedi Yoğun BYF'},
  {'symbol': 'Z30KP', 'name': 'Ziraat Portföy Katılım 30 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'ZEDUR', 'name': 'Zedur Enerji Elektrik Üretim A.Ş.'},
  {'symbol': 'ZELOT', 'name': 'Ziraat Portföy BIST 50-30 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'ZERGY', 'name': 'Zeray GYO A.Ş.'},
  {'symbol': 'ZGOLD', 'name': 'Ziraat Portföy Altın BYF'},
  {'symbol': 'ZGYO', 'name': 'Zirve GYO'},
  {'symbol': 'ZOREN', 'name': 'Zorlu Enerji Elektirik Üretim A.Ş.'},
  {'symbol': 'ZPBDL', 'name': 'Ziraat Portföy BIST Banka Dışı Likit 10 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'ZPLIB', 'name': 'Ziraat Portföy BIST Likit Banka Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'ZPT10', 'name': 'Ziraat Portföy Yıldız Pazar Teknoloji ve İletişim 10 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'ZPX30', 'name': 'Ziraat Portföy BIST 30 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'ZRE20', 'name': 'Ziraat Portföy Risk Eşit Banka Dışı 20 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'ZRGYO', 'name': 'Ziraat GYO A.Ş.'},
  {'symbol': 'ZSR25', 'name': 'Ziraat Portföy BIST Sürdürülebilirlik 25 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'ZTLRF', 'name': 'Ziraat Portföy TLREF BYF'},
  {'symbol': 'ZTLRK', 'name': 'Ziraat Portföy TLREF Katılım BYF'},
  {'symbol': 'ZTM25', 'name': 'Ziraat Portföy BIST Temettü 25 Endeksi Hisse Senedi Yoğun BYF'},
];

List<Map<String, String>> kBistStocks = List<Map<String, String>>.from(_baseBistStocks);

void syncBistStocksWithIpoItems(List<IpoItem> ipoItems) {
  final merged = <Map<String, String>>[];
  final seenSymbols = <String>{};

  for (final entry in _baseBistStocks) {
    final symbol = (entry['symbol'] ?? '').toString().toUpperCase();
    if (symbol.isEmpty || seenSymbols.contains(symbol)) continue;
    seenSymbols.add(symbol);
    merged.add(Map<String, String>.from(entry));
  }

  for (final item in ipoItems.where((item) =>
      item.status == IpoStatus.trading && item.symbol.isNotEmpty)) {
    final symbol = item.symbol.toUpperCase();
    if (seenSymbols.contains(symbol)) continue;
    seenSymbols.add(symbol);
    final name = item.companyName.trim().isNotEmpty
        ? item.companyName.trim()
        : symbol;
    merged.add({'symbol': symbol, 'name': name});
  }

  merged.sort((a, b) =>
      (a['symbol'] ?? '').toLowerCase().compareTo((b['symbol'] ?? '').toLowerCase()));
  kBistStocks = merged;
}

/// Borsa İstanbul BIST 100 Endeks Bileşenleri
/// Kaynak: Borsa İstanbul resmi endeks listesi
/// Son güncelleme: Eylül 2026 revizyonu (01.05.2026 – 30.09.2026 dönemi)
/// Değişiklikler: AGHOL, TABGD, TUREX çıkarıldı; ODINE, IEYHO, ESEN eklendi.
const List<String> kBist100Symbols = [
  // ── Bankacılık ──────────────────────────────────────────
  'AKBNK', 'ALBRK', 'GARAN', 'HALKB', 'ICBCT',
  'ISCTR', 'ISFIN', 'ISKUR', 'KLNMA', 'SKBNK',
  'TSKB', 'VAKBN', 'YKBNK',
  // ── Holding & Yatırım ───────────────────────────────────
  // AGHOL çıkarıldı (Eylül 2026 revizyonu)
  'DOHOL', 'GLYHO', 'KCHOL', 'KOZAA',
  'MPARK', 'SAHOL', 'TKFEN',
  // ── Sanayi & Üretim ─────────────────────────────────────
  'ARCLK', 'ASELS', 'ASTOR', 'CCOLA', 'CIMSA',
  'DEVA', 'EREGL', 'FROTO', 'GUBRF', 'KRDMD',
  'OTKAR', 'PETKM', 'PGSUS', 'SASA', 'THYAO',
  'TOASO', 'TTRAK', 'TUPRS', 'VESTL',
  // ── Enerji ──────────────────────────────────────────────
  'AKFYE', 'AKSEN', 'AYDEM', 'AYEN', 'CWENE',
  'ENKAI', 'EUPWR', 'GWIND', 'IZENR', 'ODAS',
  'ZOREN',
  // ── Eylül 2026 Eklenen Enerji: ESEN ─────────────────────
  'ESEN',  // Esenboğa Elektrik
  // ── Perakende & Tüketim ─────────────────────────────────
  'BIMAS', 'LOGO', 'MAVI', 'MGROS', 'SOKM',
  'ULKER',
  // ── Gayrimenkul ─────────────────────────────────────────
  'EKGYO', 'ISGYO', 'RYGYO', 'TRGYO',
  // ── Teknoloji & Telekom ──────────────────────────────────
  'ARDYZ', 'NETAS', 'SMART', 'TCELL', 'TTKOM',
  // ── Eylül 2026 Eklenen Teknoloji: ODINE ─────────────────
  'ODINE', // Odine Teknoloji
  // ── Sigorta & Finans ────────────────────────────────────
  'AKGRT', 'ANSGR', 'ISMEN',
  // ── Otomotiv ────────────────────────────────────────────
  'DOAS', 'KARSN',
  // ── Kimya & İlaç ────────────────────────────────────────
  'AKSA', 'BRISA', 'ECZYT', 'HEKTS',
  // ── Gıda & İçecek ───────────────────────────────────────
  // TABGD çıkarıldı (Eylül 2026 revizyonu)
  'AEFES', 'AYGAZ', 'TATGD', 'TUKAS',
  // ── Enerji Holding: IEYHO ───────────────────────────────
  'IEYHO', // Işıklar Enerji Yapı Holding
  // ── Çimento & İnşaat ────────────────────────────────────
  'BUCIM', 'NUHCM',
  // ── Tekstil & Diğer ─────────────────────────────────────
  // TUREX çıkarıldı (Eylül 2026 revizyonu)
  'ALKIM', 'ALTNY', 'BERA', 'BFREN', 'CANTE',
  'EGEEN', 'GENIL', 'GESAN', 'GOLTS', 'KORDS',
  'KOZAL', 'MIATK', 'PENTA', 'POLHO', 'SISE',
  'TAVHL', 'TMSN', 'TRILC', 'ULUUN',
];

