// BIST 500 — Tam hisse listesi (Kaynak: Borsa İstanbul)
const List<Map<String, String>> kBistStocks = [
  {'symbol': 'A1CAP', 'name': 'A1 Capital'},
  {'symbol': 'A1YEN', 'name': 'A1 Yenilenebilir Enerji'},
  {'symbol': 'AAGYO', 'name': 'Alarko GYO'},
  {'symbol': 'ADEL', 'name': 'Adel Kalemcilik'},
  {'symbol': 'ADESE', 'name': 'Adese AVM'},
  {'symbol': 'ADGYO', 'name': 'Adımlar GYO'},
  {'symbol': 'AEFES', 'name': 'Anadolu Efes'},
  {'symbol': 'AFYON', 'name': 'Afyon Çimento'},
  {'symbol': 'AGESA', 'name': 'Agesa Hayat Emeklilik'},
  {'symbol': 'AGHOL', 'name': 'AG Anadolu Grubu Holding'},
  {'symbol': 'AGROT', 'name': 'Agrot'},
  {'symbol': 'AHGAZ', 'name': 'Akenerji Gaz'},
  {'symbol': 'AHSGY', 'name': 'Ahlatcı GYO'},
  {'symbol': 'AKBNK', 'name': 'Akbank'},
  {'symbol': 'AKCNS', 'name': 'Akçansa Çimento'},
  {'symbol': 'AKENR', 'name': 'Akenerji Elektrik'},
  {'symbol': 'AKFGY', 'name': 'Akfen GYO'},
  {'symbol': 'AKFIS', 'name': 'Akfen Holding'},
  {'symbol': 'AKFYE', 'name': 'Akfen Yenilenebilir Enerji'},
  {'symbol': 'AKGRT', 'name': 'Aksigorta'},
  {'symbol': 'AKHAN', 'name': 'Ak-Han GYO'},
  {'symbol': 'AKSA', 'name': 'Aksa Akrilik'},
  {'symbol': 'AKSEN', 'name': 'Aksa Enerji'},
  {'symbol': 'AKSGY', 'name': 'Aksa GYO'},
  {'symbol': 'AKSUE', 'name': 'Aksu Enerji'},
  {'symbol': 'ALARK', 'name': 'Alarko Holding'},
  {'symbol': 'ALBRK', 'name': 'Albaraka Türk'},
  {'symbol': 'ALCAR', 'name': 'Alcar Araç Üstü'},
  {'symbol': 'ALCTL', 'name': 'Alcatel Lucent'},
  {'symbol': 'ALFAS', 'name': 'Alfa Solar'},
  {'symbol': 'ALGYO', 'name': 'Alfa GYO'},
  {'symbol': 'ALKA', 'name': 'Alka Kimya'},
  {'symbol': 'ALKIM', 'name': 'Alkim Kimya'},
  {'symbol': 'ALKLC', 'name': 'Alkılıç Gıda'},
  {'symbol': 'ALTNY', 'name': 'Altınyıldız Mensucat'},
  {'symbol': 'ALVES', 'name': 'Alves Holding'},
  {'symbol': 'ANACM', 'name': 'Anadolu Cam'},
  {'symbol': 'ANELE', 'name': 'Aneles Enerji'},
  {'symbol': 'ANGEN', 'name': 'Anadolu Genetik'},
  {'symbol': 'ANHYT', 'name': 'Anadolu Hayat Emeklilik'},
  {'symbol': 'ANSGR', 'name': 'Anadolu Sigorta'},
  {'symbol': 'ARASE', 'name': 'Arase'},
  {'symbol': 'ARCLK', 'name': 'Arçelik'},
  {'symbol': 'ARDYZ', 'name': 'Ardıç Yazılım'},
  {'symbol': 'ARENA', 'name': 'Arena Bilgisayar'},
  {'symbol': 'ARFYE', 'name': 'Arfin Yatırım'},
  {'symbol': 'ARMGD', 'name': 'Armada Bilgisayar'},
  {'symbol': 'ARSAN', 'name': 'Arsan Tekstil'},
  {'symbol': 'ARTMS', 'name': 'Artemas'},
  {'symbol': 'ARZUM', 'name': 'Arzum Elektrikli Ev Aletleri'},
  {'symbol': 'ASELS', 'name': 'Aselsan'},
  {'symbol': 'ASGYO', 'name': 'Aslancık GYO'},
  {'symbol': 'ASTOR', 'name': 'Astor Enerji'},
  {'symbol': 'ASUZU', 'name': 'Anadolu Isuzu'},
  {'symbol': 'ATAKP', 'name': 'Atakaş Holding'},
  {'symbol': 'ATATP', 'name': 'Ata Tarım'},
  {'symbol': 'ATATR', 'name': 'Ata GYO'},
  {'symbol': 'AVGYO', 'name': 'Avrasya GYO'},
  {'symbol': 'AVHOL', 'name': 'Avrasya Holding'},
  {'symbol': 'AVOD', 'name': 'A.V.O.D Kurutulmuş Gıda'},
  {'symbol': 'AVPGY', 'name': 'Avicenna GYO'},
  {'symbol': 'AYCES', 'name': 'Altınyunus Çeşme'},
  {'symbol': 'AYDEM', 'name': 'Aydem Enerji'},
  {'symbol': 'AYEN', 'name': 'Aydem Yenilenebilir Enerji'},
  {'symbol': 'AYGAZ', 'name': 'Aygaz'},
  {'symbol': 'AZTEK', 'name': 'Aztek'},
  {'symbol': 'BAGFS', 'name': 'Bagfaş Bandırma Gübre'},
  {'symbol': 'BAHKM', 'name': 'Bahçeşehir Koleji'},
  {'symbol': 'BALSU', 'name': 'Balsu Gıda'},
  {'symbol': 'BANVT', 'name': 'Banvit'},
  {'symbol': 'BARMA', 'name': 'Barhane Holding'},
  {'symbol': 'BASGZ', 'name': 'Baştaş Başkent'},
  {'symbol': 'BAYRK', 'name': 'Bayrak'},
  {'symbol': 'BEGYO', 'name': 'Beka GYO'},
  {'symbol': 'BERA', 'name': 'Bera Holding'},
  {'symbol': 'BESLR', 'name': 'Beslerbaşı'},
  {'symbol': 'BESTE', 'name': 'Beste Gıda'},
  {'symbol': 'BEYAZ', 'name': 'Beyaz Filo'},
  {'symbol': 'BFREN', 'name': 'Bosch Fren'},
  {'symbol': 'BIENY', 'name': 'Bien Yapı'},
  {'symbol': 'BIGCH', 'name': 'Big Chef'},
  {'symbol': 'BIGEN', 'name': 'Biogenik'},
  {'symbol': 'BIGTK', 'name': 'Big Teknoloji'},
  {'symbol': 'BIMAS', 'name': 'BİM Mağazalar'},
  {'symbol': 'BINBN', 'name': 'Binbirbuçuk'},
  {'symbol': 'BINHO', 'name': 'Bin Holding'},
  {'symbol': 'BIOEN', 'name': 'Bioenerji'},
  {'symbol': 'BJKAS', 'name': 'Beşiktaş Futbol Yatırımları'},
  {'symbol': 'BLCYT', 'name': 'Bilici Yatırım'},
  {'symbol': 'BLUME', 'name': 'Blume'},
  {'symbol': 'BMSCH', 'name': 'BMS Çelik'},
  {'symbol': 'BMSTL', 'name': 'BMS Lojistik'},
  {'symbol': 'BNTAS', 'name': 'Bantaş'},
  {'symbol': 'BOBET', 'name': 'Boğaziçi Beton'},
  {'symbol': 'BORLS', 'name': 'Borluş'},
  {'symbol': 'BORSK', 'name': 'Borsuk Kağıt'},
  {'symbol': 'BOSSA', 'name': 'Bossa Ticaret'},
  {'symbol': 'BRISA', 'name': 'Brisa Bridgestone'},
  {'symbol': 'BRKVY', 'name': 'Berkay Yatırım'},
  {'symbol': 'BRLSM', 'name': 'Birleşim Mühendislik'},
  {'symbol': 'BRSAN', 'name': 'Borçelik Çelik'},
  {'symbol': 'BRYAT', 'name': 'Burç Yatırım'},
  {'symbol': 'BSOKE', 'name': 'Batı Söke Çimento'},
  {'symbol': 'BTCIM', 'name': 'Batıçim Batı Anadolu'},
  {'symbol': 'BUCIM', 'name': 'Bursa Çimento'},
  {'symbol': 'BULGS', 'name': 'Bulgurlu'},
  {'symbol': 'BURCE', 'name': 'Burçelik'},
  {'symbol': 'BVSAN', 'name': 'Birleşik Vagon'},
  {'symbol': 'CANTE', 'name': 'Can Tarım'},
  {'symbol': 'CATES', 'name': 'Çateks'},
  {'symbol': 'CCOLA', 'name': 'Coca-Cola İçecek'},
  {'symbol': 'CELHA', 'name': 'Çelha'},
  {'symbol': 'CEMAS', 'name': 'Cemaş Döküm'},
  {'symbol': 'CEMTS', 'name': 'Çimentaş'},
  {'symbol': 'CEMZY', 'name': 'Çemzy'},
  {'symbol': 'CGCAM', 'name': 'Çayırova Cam'},
  {'symbol': 'CIMSA', 'name': 'Çimsa Çimento'},
  {'symbol': 'CLEBI', 'name': 'Çelebi Hava Hizmetleri'},
  {'symbol': 'CMBTN', 'name': 'Çimbeton'},
  {'symbol': 'CONSE', 'name': 'Consus'},
  {'symbol': 'CRFSA', 'name': 'Carrefoursa'},
  {'symbol': 'CVKMD', 'name': 'CVK Madencilik'},
  {'symbol': 'CWENE', 'name': 'CW Enerji'},
  {'symbol': 'DAGI', 'name': 'Dagi Giyim'},
  {'symbol': 'DAPGM', 'name': 'DAP Gayrimenkul'},
  {'symbol': 'DARDL', 'name': 'Dardanel Önentaş'},
  {'symbol': 'DCTTR', 'name': 'Doçtürk'},
  {'symbol': 'DENGE', 'name': 'Denge Holding'},
  {'symbol': 'DERHL', 'name': 'Derici Holding'},
  {'symbol': 'DESA', 'name': 'Desa Deri'},
  {'symbol': 'DEVA', 'name': 'Deva Holding'},
  {'symbol': 'DGATE', 'name': 'Datagate Bilgisayar'},
  {'symbol': 'DGNMO', 'name': 'Doğan Müzik'},
  {'symbol': 'DITAS', 'name': 'Ditaş Doğan'},
  {'symbol': 'DMRGD', 'name': 'Demirağ'},
  {'symbol': 'DMSAS', 'name': 'Demisaş Döküm'},
  {'symbol': 'DNISI', 'name': 'Deniz İnşaat'},
  {'symbol': 'DOAS', 'name': 'Doğuş Otomotiv'},
  {'symbol': 'DOCO', 'name': 'Doğan Şirketler'},
  {'symbol': 'DOFER', 'name': 'Doğan Fermantasyon'},
  {'symbol': 'DOFRB', 'name': 'Doğan Fren'},
  {'symbol': 'DOHOL', 'name': 'Doğan Holding'},
  {'symbol': 'DUNYH', 'name': 'Dünya Holding'},
  {'symbol': 'DURDO', 'name': 'Durdoğan'},
  {'symbol': 'DURKN', 'name': 'Dürkanlı'},
  {'symbol': 'DYOBY', 'name': 'DYO Boya'},
  {'symbol': 'DZGYO', 'name': 'Deniz GYO'},
  {'symbol': 'EBEBK', 'name': 'Ebe Bekleme'},
  {'symbol': 'ECILC', 'name': 'Eczacıbaşı İlaç'},
  {'symbol': 'ECOGR', 'name': 'Ekohisse'},
  {'symbol': 'ECZYT', 'name': 'Eczacıbaşı Yatırım'},
  {'symbol': 'EDATA', 'name': 'E-Data Teknoloji'},
  {'symbol': 'EDIP', 'name': 'Edip İplik'},
  {'symbol': 'EFOR', 'name': 'Efor Enerji'},
  {'symbol': 'EGEEN', 'name': 'Ege Endüstri'},
  {'symbol': 'EGEGY', 'name': 'Ege Gübre'},
  {'symbol': 'EGEPO', 'name': 'Ege Profil'},
  {'symbol': 'EGGUB', 'name': 'Ege Gübre Sanayi'},
  {'symbol': 'EGPRO', 'name': 'EG Pro'},
  {'symbol': 'EKDMR', 'name': 'Ereğli Köyü Demir'},
  {'symbol': 'EKGYO', 'name': 'Emlak Konut GYO'},
  {'symbol': 'EKOS', 'name': 'Ekos Holding'},
  {'symbol': 'EKSUN', 'name': 'Eksun Gıda'},
  {'symbol': 'ELITE', 'name': 'Elite Naturel'},
  {'symbol': 'EMKEL', 'name': 'Emkel Elektrik'},
  {'symbol': 'EMPAE', 'name': 'Empae'},
  {'symbol': 'ENDAE', 'name': 'Enda Enerji'},
  {'symbol': 'ENERY', 'name': 'Enerya Enerji'},
  {'symbol': 'ENJSA', 'name': 'Enerjisa Enerji'},
  {'symbol': 'ENKAI', 'name': 'Enka İnşaat'},
  {'symbol': 'ENSRI', 'name': 'Ensari'},
  {'symbol': 'ENTRA', 'name': 'Entra Enerji'},
  {'symbol': 'EPLAS', 'name': 'Egeplast'},
  {'symbol': 'ERCB', 'name': 'Erceb'},
  {'symbol': 'EREGL', 'name': 'Ereğli Demir Çelik'},
  {'symbol': 'ESCAR', 'name': 'Escort Teknoloji'},
  {'symbol': 'ESCOM', 'name': 'Escort'},
  {'symbol': 'ESEN', 'name': 'Esen'},
  {'symbol': 'ETILR', 'name': 'Etiler Gıda'},
  {'symbol': 'EUPWR', 'name': 'EuroPower Enerji'},
  {'symbol': 'EUREN', 'name': 'Eurenco'},
  {'symbol': 'EYGYO', 'name': 'Eyüp Sultan GYO'},
  {'symbol': 'FADE', 'name': 'Fade'},
  {'symbol': 'FENER', 'name': 'Fenerbahçe Futbol'},
  {'symbol': 'FMIZP', 'name': 'Fimizpazarlama'},
  {'symbol': 'FONET', 'name': 'Fonet Bilgi Teknolojileri'},
  {'symbol': 'FORMT', 'name': 'Format'},
  {'symbol': 'FORTE', 'name': 'Forte'},
  {'symbol': 'FRIGO', 'name': 'Frigo-Pak Gıda'},
  {'symbol': 'FRMPL', 'name': 'Fortemple'},
  {'symbol': 'FROTO', 'name': 'Ford Otosan'},
  {'symbol': 'FZLGY', 'name': 'Fazıl GYO'},
  {'symbol': 'GARAN', 'name': 'Garanti BBVA'},
  {'symbol': 'GARFA', 'name': 'Garanti Faktoring'},
  {'symbol': 'GEDIK', 'name': 'Gedik Yatırım'},
  {'symbol': 'GEDZA', 'name': 'Gedik Otomotiv'},
  {'symbol': 'GENIL', 'name': 'Genilmas'},
  {'symbol': 'GENKM', 'name': 'Genkima'},
  {'symbol': 'GENTS', 'name': 'Gents'},
  {'symbol': 'GEREL', 'name': 'Gerelsan'},
  {'symbol': 'GESAN', 'name': 'Gesan'},
  {'symbol': 'GIPTA', 'name': 'Gipta'},
  {'symbol': 'GLCVY', 'name': 'Galata Cavy'},
  {'symbol': 'GLRMK', 'name': 'Güler Yatırım'},
  {'symbol': 'GLRYH', 'name': 'Güler Holding'},
  {'symbol': 'GLYHO', 'name': 'Global Yatırım Holding'},
  {'symbol': 'GMTAS', 'name': 'Gümüştaş'},
  {'symbol': 'GOKNR', 'name': 'Göknur Holding'},
  {'symbol': 'GOLTS', 'name': 'Göltas Göller'},
  {'symbol': 'GOODY', 'name': 'Goodyear'},
  {'symbol': 'GOZDE', 'name': 'Gözde Girişim'},
  {'symbol': 'GRSEL', 'name': 'Gursel Turizm'},
  {'symbol': 'GRTHO', 'name': 'Greka Holding'},
  {'symbol': 'GSDHO', 'name': 'GSD Holding'},
  {'symbol': 'GSRAY', 'name': 'Galatasaray Sportif'},
  {'symbol': 'GUBRF', 'name': 'Gübre Fabrikaları'},
  {'symbol': 'GUNDG', 'name': 'Gündoğdu Holding'},
  {'symbol': 'GWIND', 'name': 'Güneş Wind'},
  {'symbol': 'GZNMI', 'name': 'Gaziantep'},
  {'symbol': 'HALKB', 'name': 'Halkbank'},
  {'symbol': 'HATEK', 'name': 'Hateks Hatay'},
  {'symbol': 'HATSN', 'name': 'Hatsan'},
  {'symbol': 'HDFGS', 'name': 'Hedef Girişim'},
  {'symbol': 'HEDEF', 'name': 'Hedef Holding'},
  {'symbol': 'HEKTS', 'name': 'Hektaş'},
  {'symbol': 'HKTM', 'name': 'Hektaş Teknoloji'},
  {'symbol': 'HLGYO', 'name': 'Halk GYO'},
  {'symbol': 'HOROZ', 'name': 'Horoz Lojistik'},
  {'symbol': 'HRKET', 'name': 'Hareket'},
  {'symbol': 'HTTBT', 'name': 'Hattat Holding'},
  {'symbol': 'HUNER', 'name': 'Hüner'},
  {'symbol': 'HURGZ', 'name': 'Hürriyet Gazetecilik'},
  {'symbol': 'ICBCT', 'name': 'İç Beton'},
  {'symbol': 'IEYHO', 'name': 'İEYHO'},
  {'symbol': 'IHAAS', 'name': 'İhlas Finans'},
  {'symbol': 'IHGZT', 'name': 'İhlas Gazetecilik'},
  {'symbol': 'IHLAS', 'name': 'İhlas Holding'},
  {'symbol': 'IHLGM', 'name': 'İhlas Gayrimenkul'},
  {'symbol': 'IMASM', 'name': 'İmas Motor'},
  {'symbol': 'INDES', 'name': 'İndeks Bilgisayar'},
  {'symbol': 'INFO', 'name': 'İnfo Yatırım'},
  {'symbol': 'INGRM', 'name': 'İngram Micro'},
  {'symbol': 'INTEM', 'name': 'İntem'},
  {'symbol': 'INVEO', 'name': 'İnveo Yatırım'},
  {'symbol': 'INVES', 'name': 'İnves Bilgisayar'},
  {'symbol': 'ISCTR', 'name': 'İş Bankası C'},
  {'symbol': 'ISDMR', 'name': 'İskenderun Demir'},
  {'symbol': 'ISFIN', 'name': 'İş Finansal Kiralama'},
  {'symbol': 'ISGSY', 'name': 'İş Girişim Sermayesi'},
  {'symbol': 'ISGYO', 'name': 'İş GYO'},
  {'symbol': 'ISKPL', 'name': 'İskiplik'},
  {'symbol': 'ISMEN', 'name': 'İş Yatırım Menkul'},
  {'symbol': 'IZENR', 'name': 'İzdemir Enerji'},
  {'symbol': 'IZFAS', 'name': 'İzmir Fırça'},
  {'symbol': 'IZMDC', 'name': 'İzmirim Demir Çelik'},
  {'symbol': 'JANTS', 'name': 'Jantsa Jant'},
  {'symbol': 'KAPLM', 'name': 'Kaplama'},
  {'symbol': 'KAREL', 'name': 'Karel Elektronik'},
  {'symbol': 'KARSN', 'name': 'Karsan Otomotiv'},
  {'symbol': 'KARTN', 'name': 'Kartonsan'},
  {'symbol': 'KATMR', 'name': 'Katmerciler'},
  {'symbol': 'KAYSE', 'name': 'Kayseri Şeker'},
  {'symbol': 'KBORU', 'name': 'Kayabaşı Boru'},
  {'symbol': 'KCAER', 'name': 'Koca Enerji'},
  {'symbol': 'KCHOL', 'name': 'Koç Holding'},
  {'symbol': 'KFEIN', 'name': 'Kafe İnternational'},
  {'symbol': 'KGYO', 'name': 'Kırklareli GYO'},
  {'symbol': 'KIMMR', 'name': 'Kimmer'},
  {'symbol': 'KLGYO', 'name': 'Kiler GYO'},
  {'symbol': 'KLKIM', 'name': 'Klik Kimya'},
  {'symbol': 'KLMSN', 'name': 'Klimasan Klima'},
  {'symbol': 'KLRHO', 'name': 'Kiler Holding'},
  {'symbol': 'KLSER', 'name': 'Kliser'},
  {'symbol': 'KLSYN', 'name': 'Kılıç Şarap'},
  {'symbol': 'KLYPV', 'name': 'Kalyon PV'},
  {'symbol': 'KMPUR', 'name': 'Kombassan Holding'},
  {'symbol': 'KNFRT', 'name': 'Konfirst'},
  {'symbol': 'KOCMT', 'name': 'Koç Enerji'},
  {'symbol': 'KONKA', 'name': 'Konkar Petrol'},
  {'symbol': 'KONYA', 'name': 'Konya Çimento'},
  {'symbol': 'KOPOL', 'name': 'Kopol'},
  {'symbol': 'KORDS', 'name': 'Kordsa'},
  {'symbol': 'KOTON', 'name': 'Koton'},
  {'symbol': 'KRDMD', 'name': 'Kardemir D'},
  {'symbol': 'KRGYO', 'name': 'Karşıyaka GYO'},
  {'symbol': 'KRONT', 'name': 'Kron Telekomünikasyon'},
  {'symbol': 'KRPLS', 'name': 'Karplus'},
  {'symbol': 'KRSTL', 'name': 'Kristal Kola'},
  {'symbol': 'KRVGD', 'name': 'Kervan Gıda'},
  {'symbol': 'KTLEV', 'name': 'Katılım Emeklilik'},
  {'symbol': 'KTSKR', 'name': 'Konya Tatko Şeker'},
  {'symbol': 'KUTPO', 'name': 'Kümaş Manyezit'},
  {'symbol': 'KUYAS', 'name': 'Kuyas'},
  {'symbol': 'KZBGY', 'name': 'Kuzey Bolu'},
  {'symbol': 'KZGYO', 'name': 'Kuzey GYO'},
  {'symbol': 'LIDER', 'name': 'Lider Faktoring'},
  {'symbol': 'LIDFA', 'name': 'Lider Faktoring A'},
  {'symbol': 'LILAK', 'name': 'Lilak'},
  {'symbol': 'LINK', 'name': 'Link Bilgisayar'},
  {'symbol': 'LKMNH', 'name': 'Lokman Hekim'},
  {'symbol': 'LMKDC', 'name': 'Limak Doğalgaz'},
  {'symbol': 'LOGO', 'name': 'Logo Yazılım'},
  {'symbol': 'LRSHO', 'name': 'Larsa Holding'},
  {'symbol': 'LXGYO', 'name': 'Lüxtera GYO'},
  {'symbol': 'LYDHO', 'name': 'Lider Holding'},
  {'symbol': 'MAALT', 'name': 'M.A. Altın'},
  {'symbol': 'MACKO', 'name': 'Macko'},
  {'symbol': 'MAGEN', 'name': 'Magna'},
  {'symbol': 'MAKIM', 'name': 'Makim'},
  {'symbol': 'MAKTK', 'name': 'Mak Teknik'},
  {'symbol': 'MANAS', 'name': 'Manas'},
  {'symbol': 'MARBL', 'name': 'Marbella'},
  {'symbol': 'MARKA', 'name': 'Marka Yatırım'},
  {'symbol': 'MARMR', 'name': 'Marmaris Altınyunus'},
  {'symbol': 'MARTI', 'name': 'Martı Otel'},
  {'symbol': 'MAVI', 'name': 'Mavi Giyim'},
  {'symbol': 'MCARD', 'name': 'Mastercard'},
  {'symbol': 'MEDTR', 'name': 'Meditera'},
  {'symbol': 'MEGMT', 'name': 'Mega Menkul'},
  {'symbol': 'MEKAG', 'name': 'Meka Gıda'},
  {'symbol': 'MERCN', 'name': 'Mercan'},
  {'symbol': 'MERIT', 'name': 'Merit Turizm'},
  {'symbol': 'MERKO', 'name': 'Merko Gıda'},
  {'symbol': 'METRO', 'name': 'Metro Ticaret'},
  {'symbol': 'MEYSU', 'name': 'Mey Su'},
  {'symbol': 'MGROS', 'name': 'Migros'},
  {'symbol': 'MHRGY', 'name': 'Mahir GYO'},
  {'symbol': 'MIATK', 'name': 'Mia Teknoloji'},
  {'symbol': 'MNDRS', 'name': 'Menderes Tekstil'},
  {'symbol': 'MNDTR', 'name': 'Meindert'},
  {'symbol': 'MOBTL', 'name': 'Mobil Telekom'},
  {'symbol': 'MOGAN', 'name': 'Mogan'},
  {'symbol': 'MOPAS', 'name': 'Mopaş'},
  {'symbol': 'MPARK', 'name': 'MLP Sağlık'},
  {'symbol': 'MRGYO', 'name': 'Mert GYO'},
  {'symbol': 'MRSHL', 'name': 'Marshall Boya'},
  {'symbol': 'MSGYO', 'name': 'Metropol GYO'},
  {'symbol': 'MTRKS', 'name': 'Metriksel'},
  {'symbol': 'NATEN', 'name': 'Naturel Enerji'},
  {'symbol': 'NETAS', 'name': 'Netaş Telekomünikasyon'},
  {'symbol': 'NETCD', 'name': 'Netcad'},
  {'symbol': 'NIBAS', 'name': 'Nibas'},
  {'symbol': 'NTGAZ', 'name': 'Naturelgaz'},
  {'symbol': 'NTHOL', 'name': 'Net Holding'},
  {'symbol': 'NUGYO', 'name': 'Nurol GYO'},
  {'symbol': 'NUHCM', 'name': 'Nuh Çimento'},
  {'symbol': 'OBAMS', 'name': 'Obams'},
  {'symbol': 'ODAS', 'name': 'Odaş Elektrik'},
  {'symbol': 'ODINE', 'name': 'Odine'},
  {'symbol': 'OFSYM', 'name': 'Ofis Yönetim'},
  {'symbol': 'ONCSM', 'name': 'Öncü Girişim'},
  {'symbol': 'ONRYT', 'name': 'Onur Rüzgar'},
  {'symbol': 'ORGE', 'name': 'Orge Enerji'},
  {'symbol': 'OSMEN', 'name': 'Osman'},
  {'symbol': 'OSTIM', 'name': 'OSTİM Endüstriyel'},
  {'symbol': 'OTKAR', 'name': 'Otokar'},
  {'symbol': 'OTTO', 'name': 'Otto'},
  {'symbol': 'OYAKC', 'name': 'Oyak Çimento'},
  {'symbol': 'OYYAT', 'name': 'Oyak Yatırım'},
  {'symbol': 'OZATD', 'name': 'Özata Denizcilik'},
  {'symbol': 'OZGYO', 'name': 'Özgün GYO'},
  {'symbol': 'OZKGY', 'name': 'Özak GYO'},
  {'symbol': 'OZSUB', 'name': 'Özsu Bilişim'},
  {'symbol': 'OZYSR', 'name': 'Özyaşar'},
  {'symbol': 'PAGYO', 'name': 'Pasha GYO'},
  {'symbol': 'PAHOL', 'name': 'Pasha Holding'},
  {'symbol': 'PAPIL', 'name': 'Papilion'},
  {'symbol': 'PARSN', 'name': 'Parsan'},
  {'symbol': 'PASEU', 'name': 'Pasifik'},
  {'symbol': 'PATEK', 'name': 'Patek'},
  {'symbol': 'PCILT', 'name': 'PC İletişim'},
  {'symbol': 'PEKGY', 'name': 'Pek GYO'},
  {'symbol': 'PENGD', 'name': 'Penguengd'},
  {'symbol': 'PENTA', 'name': 'Penta Teknoloji'},
  {'symbol': 'PETKM', 'name': 'Petkim'},
  {'symbol': 'PETUN', 'name': 'Pınar Et'},
  {'symbol': 'PGSUS', 'name': 'Pegasus'},
  {'symbol': 'PINSU', 'name': 'Pınar Su'},
  {'symbol': 'PKART', 'name': 'Plastik Kart'},
  {'symbol': 'PKENT', 'name': 'Petrokent Turizm'},
  {'symbol': 'PLTUR', 'name': 'Poltur'},
  {'symbol': 'PNLSN', 'name': 'Pınar Süt'},
  {'symbol': 'PNSUT', 'name': 'Pınar Süt Mamulleri'},
  {'symbol': 'POLHO', 'name': 'Polisan Holding'},
  {'symbol': 'POLTK', 'name': 'Politeknik'},
  {'symbol': 'PRDGS', 'name': 'Pardus'},
  {'symbol': 'PRKAB', 'name': 'Pimaş Plastik'},
  {'symbol': 'PRKME', 'name': 'Peker'},
  {'symbol': 'PSGYO', 'name': 'Panora GYO'},
  {'symbol': 'QUAGR', 'name': 'Qua Granite'},
  {'symbol': 'RALYH', 'name': 'Ray Holding'},
  {'symbol': 'RAYSG', 'name': 'Ray Sigorta'},
  {'symbol': 'REEDR', 'name': 'Reedr'},
  {'symbol': 'RGYAS', 'name': 'Reysaş GYO'},
  {'symbol': 'RTALB', 'name': 'Rota Liman'},
  {'symbol': 'RUBNS', 'name': 'Rubenis'},
  {'symbol': 'RUZYE', 'name': 'Rüzgar Enerji'},
  {'symbol': 'RYGYO', 'name': 'Reyhan GYO'},
  {'symbol': 'RYSAS', 'name': 'Reysaş Taşımacılık'},
  {'symbol': 'SAFKR', 'name': 'Safkar'},
  {'symbol': 'SAHOL', 'name': 'Sabancı Holding'},
  {'symbol': 'SANFM', 'name': 'Sanifoam'},
  {'symbol': 'SARKY', 'name': 'Sarkuysan'},
  {'symbol': 'SASA', 'name': 'Sasa Polyester'},
  {'symbol': 'SAYAS', 'name': 'Sayas'},
  {'symbol': 'SDTTR', 'name': 'Sedat Toraman'},
  {'symbol': 'SEGMN', 'name': 'Segmen'},
  {'symbol': 'SEGYO', 'name': 'Seğmen GYO'},
  {'symbol': 'SELEC', 'name': 'Selçuk Ecza'},
  {'symbol': 'SELVA', 'name': 'Selva Gıda'},
  {'symbol': 'SERNT', 'name': 'Seranit'},
  {'symbol': 'SISE', 'name': 'Şişe Cam'},
  {'symbol': 'SKBNK', 'name': 'Şekerbank'},
  {'symbol': 'SKTAS', 'name': 'Söktaş Tekstil'},
  {'symbol': 'SKYMD', 'name': 'Sky Maden'},
  {'symbol': 'SMART', 'name': 'Smart Güneş'},
  {'symbol': 'SMRTG', 'name': 'Smart GYO'},
  {'symbol': 'SMRVA', 'name': 'Samir Sağlık'},
  {'symbol': 'SNGYO', 'name': 'Sinpaş GYO'},
  {'symbol': 'SNICA', 'name': 'Sönica'},
  {'symbol': 'SODA', 'name': 'Soda Sanayii'},
  {'symbol': 'SOKE', 'name': 'Söke Değirmen'},
  {'symbol': 'SOKM', 'name': 'Şok Marketler'},
  {'symbol': 'SRVGY', 'name': 'Süreyya GYO'},
  {'symbol': 'SUNTK', 'name': 'Sunteks'},
  {'symbol': 'SURGY', 'name': 'Sur Yapı GYO'},
  {'symbol': 'SUWEN', 'name': 'Süwen İç Giyim'},
  {'symbol': 'SVGYO', 'name': 'Sev GYO'},
  {'symbol': 'TABGD', 'name': 'TAB Gıda'},
  {'symbol': 'TARKM', 'name': 'Tarkim'},
  {'symbol': 'TATEN', 'name': 'Tatko Enerji'},
  {'symbol': 'TATGD', 'name': 'Tat Gıda'},
  {'symbol': 'TAVHL', 'name': 'TAV Havalimanları'},
  {'symbol': 'TBORG', 'name': 'Türk Tuborg'},
  {'symbol': 'TCELL', 'name': 'Turkcell'},
  {'symbol': 'TCKRC', 'name': 'Türk Kırmızı'},
  {'symbol': 'TEHOL', 'name': 'Tekno Holding'},
  {'symbol': 'TEKTU', 'name': 'Tek-T Uçak'},
  {'symbol': 'TERA', 'name': 'Tera Yatırım'},
  {'symbol': 'TEZOL', 'name': 'Tezol'},
  {'symbol': 'TGSAS', 'name': 'Türk Gaz'},
  {'symbol': 'THYAO', 'name': 'Türk Hava Yolları'},
  {'symbol': 'TKFEN', 'name': 'Tekfen Holding'},
  {'symbol': 'TKNSA', 'name': 'Teknosa'},
  {'symbol': 'TLMAN', 'name': 'Tailormade'},
  {'symbol': 'TMPOL', 'name': 'Temapol Polimer'},
  {'symbol': 'TMSN', 'name': 'Tamsan'},
  {'symbol': 'TNZTP', 'name': 'Tanı'},
  {'symbol': 'TOASO', 'name': 'Tofaş Oto. Fab.'},
  {'symbol': 'TRALT', 'name': 'Tür Altın'},
  {'symbol': 'TRCAS', 'name': 'Tür Çelik'},
  {'symbol': 'TRENJ', 'name': 'Türen Enerji'},
  {'symbol': 'TRGYO', 'name': 'Torunlar GYO'},
  {'symbol': 'TRMET', 'name': 'Tür Metal'},
  {'symbol': 'TSKB', 'name': 'TSKB'},
  {'symbol': 'TSPOR', 'name': 'Trabzonspor'},
  {'symbol': 'TTKOM', 'name': 'Türk Telekom'},
  {'symbol': 'TTRAK', 'name': 'Türk Traktör'},
  {'symbol': 'TUCLK', 'name': 'Tuçkağıt'},
  {'symbol': 'TUKAS', 'name': 'Tukaş'},
  {'symbol': 'TUPRS', 'name': 'Tüpraş'},
  {'symbol': 'TUREX', 'name': 'Tureks Turizm'},
  {'symbol': 'TURGG', 'name': 'Türker Proje'},
  {'symbol': 'TURSG', 'name': 'Türkiye Sigorta'},
  {'symbol': 'UCAYM', 'name': 'Uçak Servisi'},
  {'symbol': 'ULKER', 'name': 'Ülker Bisküvi'},
  {'symbol': 'ULUFA', 'name': 'Ulusoy Filo'},
  {'symbol': 'ULUSE', 'name': 'Ulusoy Elektrik'},
  {'symbol': 'ULUUN', 'name': 'Ulusoy Un'},
  {'symbol': 'UNLU', 'name': 'Ünlü Yatırım'},
  {'symbol': 'USAK', 'name': 'Uşak Seramik'},
  {'symbol': 'VAKBN', 'name': 'Vakıfbank'},
  {'symbol': 'VAKFA', 'name': 'Vakıf Finansal Kiralama'},
  {'symbol': 'VAKFN', 'name': 'Vakıf Finans'},
  {'symbol': 'VAKKO', 'name': 'Vakko Tekstil'},
  {'symbol': 'VBTYZ', 'name': 'Vbt Yazılım'},
  {'symbol': 'VERTU', 'name': 'Vertu'},
  {'symbol': 'VERUS', 'name': 'Verus'},
  {'symbol': 'VESBE', 'name': 'Vestel Beyaz Eşya'},
  {'symbol': 'VESTL', 'name': 'Vestel Elektronik'},
  {'symbol': 'VKGYO', 'name': 'Vakıf GYO'},
  {'symbol': 'VRGYO', 'name': 'Varlık GYO'},
  {'symbol': 'VSNMD', 'name': 'Vosmer'},
  {'symbol': 'YAPRK', 'name': 'Yaprak'},
  {'symbol': 'YATAS', 'name': 'Yataş'},
  {'symbol': 'YAYLA', 'name': 'Yayla Agro'},
  {'symbol': 'YEOTK', 'name': 'Yeotk'},
  {'symbol': 'YESIL', 'name': 'Yeşil Yatırım'},
  {'symbol': 'YGGYO', 'name': 'Yeni Gimat GYO'},
  {'symbol': 'YIGIT', 'name': 'Yiğit Aksesuar'},
  {'symbol': 'YKBNK', 'name': 'Yapı Kredi Bankası'},
  {'symbol': 'YKSLN', 'name': 'Yükselen Çelik'},
  {'symbol': 'YUNSA', 'name': 'Yünsa'},
  {'symbol': 'YYLGD', 'name': 'Yayla Gıda'},
  {'symbol': 'ZERGY', 'name': 'Zerya Enerji'},
  {'symbol': 'ZGYO', 'name': 'Zirve GYO'},
  {'symbol': 'ZOREN', 'name': 'Zorlu Enerji'},
  {'symbol': 'ZRGYO', 'name': 'Ziraat GYO'},
];
