import '../models/ipo_item.dart';

// BIST 500 — Tam hisse listesi (Kaynak: Borsa İstanbul)
// Borsa İstanbul'da 2026 itibarıyla bildirilen toplam hisse sayısı 610 civarındadır.
const int kBistListedCount = 610;

const List<Map<String, String>> _baseBistStocks = [
  {'symbol': 'A1CAP', 'name': 'A1 Capital'},
  {'symbol': 'A1YEN', 'name': 'A1 Yenilenebilir Enerji'},
  {'symbol': 'AAGYO', 'name': 'Alarko GYO'},
  {'symbol': 'ACSEL', 'name': 'Aciselsan Acipayam Seluloz'},
  {'symbol': 'ADEL', 'name': 'Adel Kalemcilik'},
  {'symbol': 'ADESE', 'name': 'Adese GY A.Ş'},
  {'symbol': 'ADGYO', 'name': 'Adra GYO'},
  {'symbol': 'AEFES', 'name': 'Anadolu Efes'},
  {'symbol': 'AFYON', 'name': 'Afyon Çimento'},
  {'symbol': 'AGESA', 'name': 'Agesa Hayat Emeklilik'},
  {'symbol': 'AGHOL', 'name': 'AG Anadolu Grubu Holding'},
  {'symbol': 'AGROT', 'name': 'Agrotech Yuksek Teknoloji ve Yatırım A.Ş.'},
  {'symbol': 'AGTUR', 'name': 'Agro-Tur Tarım'},
  {'symbol': 'AGYO', 'name': 'Atakule Gayrimenkul Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'AHGAZ', 'name': 'Ahlatçı Doğal Gaz Dağıtım'},
  {'symbol': 'AHGYO', 'name': 'Ahlatcı GYO'},
  {'symbol': 'AHSGY', 'name': 'Ahes GYO'},
  {'symbol': 'AKBNK', 'name': 'Akbank'},
  {'symbol': 'AKCNS', 'name': 'Akçansa Çimento'},
  {'symbol': 'AKENR', 'name': 'Akenerji Elektrik'},
  {'symbol': 'AKFGY', 'name': 'Akfen GYO'},
  {'symbol': 'AKFIS', 'name': 'Akfen İnşaat Turizm ve Ticaret A.Ş.'},
  {'symbol': 'AKFYE', 'name': 'Akfen Yenilenebilir Enerji'},
  {'symbol': 'AKGRT', 'name': 'Aksigorta'},
  {'symbol': 'AKHAN', 'name': 'Akhan Un Fabrikası ve Tarım Ürünleri'},
  {'symbol': 'AKMGY', 'name': 'Ak Merkez GYO'},
  {'symbol': 'AKSA', 'name': 'Aksa Akrilik Kimya Sanayi A.Ş.'},
  {'symbol': 'AKSEN', 'name': 'Aksa Enerji Üretim A.Ş.'},
  {'symbol': 'AKSGY', 'name': 'Aksa GYO'},
  {'symbol': 'AKSUE', 'name': 'Aksu Enerji Üretim A.Ş.'},
  {'symbol': 'AKFYE', 'name': 'Akfen Yenilenebilir Enerji'},
  {'symbol': 'AKGRT', 'name': 'Aksigorta'},
  {'symbol': 'AKHAN', 'name': 'Ak-Han GYO'},
  {'symbol': 'AKMGY', 'name': 'Ak Merkez GYO'},
  {'symbol': 'AKSA', 'name': 'Aksa Akrilik'},
  {'symbol': 'AKSEN', 'name': 'Aksa Enerji'},
  {'symbol': 'AKSGY', 'name': 'Aksa GYO'},
  {'symbol': 'AKSUE', 'name': 'Aksu Enerji'},
  {'symbol': 'AHSGY', 'name': 'Ahes GYO'},
  {'symbol': 'AKBNK', 'name': 'Akbank'},
  {'symbol': 'AKCNS', 'name': 'Akçansa Çimento'},
  {'symbol': 'AKENR', 'name': 'Akenerji Elektrik'},
  {'symbol': 'AKFGY', 'name': 'Akfen GYO'},
  {'symbol': 'AKFIS', 'name': 'Akfen Holding'},
  {'symbol': 'AKFYE', 'name': 'Akfen Yenilenebilir Enerji'},
  {'symbol': 'AKGRT', 'name': 'Aksigorta'},
  {'symbol': 'AKHAN', 'name': 'Ak-Han GYO'},
  {'symbol': 'AKMGY', 'name': 'Ak Merkez GYO'},
  {'symbol': 'AKSA', 'name': 'Aksa Akrilik'},
  {'symbol': 'AKSEN', 'name': 'Aksa Enerji'},
  {'symbol': 'AKSGY', 'name': 'Aksa GYO'},
  {'symbol': 'AKSUE', 'name': 'Aksu Enerji'},
  {'symbol': 'AGYO', 'name': 'Atakule Gayrimenkul Y.O.'},
  {'symbol': 'AHGAZ', 'name': 'Ahlatçı Doğal Gaz Dağıtım'},
  {'symbol': 'AHSGY', 'name': 'Ahlatcı GYO'},
  {'symbol': 'AKBNK', 'name': 'Akbank'},
  {'symbol': 'AKCNS', 'name': 'Akçansa Çimento'},
  {'symbol': 'AKENR', 'name': 'Akenerji Elektrik'},
  {'symbol': 'AKFGY', 'name': 'Akfen GYO'},
  {'symbol': 'AKFIS', 'name': 'Akfen Holding'},
  {'symbol': 'AKFYE', 'name': 'Akfen Yenilenebilir Enerji'},
  {'symbol': 'AKGRT', 'name': 'Aksigorta'},
  {'symbol': 'AKHAN', 'name': 'Ak-Han GYO'},
  {'symbol': 'AKMGY', 'name': 'Ak Merkez GYO'},
  {'symbol': 'AKSA', 'name': 'Aksa Akrilik'},
  {'symbol': 'AKSEN', 'name': 'Aksa Enerji'},
  {'symbol': 'AKSGY', 'name': 'Aksa GYO'},
  {'symbol': 'AKSUE', 'name': 'Aksu Enerji'},
  {'symbol': 'AKYHO', 'name': 'Akdeniz Yatırım HO'},
  {'symbol': 'ALARK', 'name': 'Alarko Holding'},
  {'symbol': 'ALBRK', 'name': 'Albaraka Türk'},
  {'symbol': 'ALBTN', 'name': 'Albayrak Hazır Beton'},
  {'symbol': 'ALCAR', 'name': 'Alcar Araç Üstü'},
  {'symbol': 'ALCTL', 'name': 'Alcatel Lucent'},
  {'symbol': 'ALFAS', 'name': 'Alfa Solar'},
  {'symbol': 'ALGYO', 'name': 'Alarko GYO'},
  {'symbol': 'ALKA', 'name': 'Alka Kimya'},
  {'symbol': 'ALKIM', 'name': 'Alkim Kimya'},
  {'symbol': 'ALKLC', 'name': 'Alkılıç Gıda'},
  {'symbol': 'ALNTF', 'name': 'Alıntı Finans'},
  {'symbol': 'ALTNY', 'name': 'Altınyıldız Mensucat'},
  {'symbol': 'ALVES', 'name': 'Alves Holding'},
  {'symbol': 'ANACM', 'name': 'Anadolu Cam'},
  {'symbol': 'ANELE', 'name': 'Aneles Enerji'},
  {'symbol': 'ANGEN', 'name': 'Anadolu Genetik'},
  {'symbol': 'ANHYT', 'name': 'Anadolu Hayat Emeklilik'},
  {'symbol': 'ANSGR', 'name': 'Anadolu Sigorta'},
  {'symbol': 'APBDL', 'name': 'Ak Portföy BIST Banka Dışı Likit 10 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'APGLD', 'name': 'Ak Portföy Altın Katılım Borsa Yatırım Fonu'},
  {'symbol': 'APLIB', 'name': 'Ak Portföy BIST Likit Banka Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'APMDL', 'name': 'Ak Portföy BIST 100 Endeksi Model Portföy Hisse Senedi Yoğun BYF'},
  {'symbol': 'APX30', 'name': 'Ak Portföy BIST 30 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'ARASE', 'name': 'Doğu Aras Enerji'},
  {'symbol': 'ARCLK', 'name': 'Arçelik'},
  {'symbol': 'ARDYZ', 'name': 'Ardıç Yazılım'},
  {'symbol': 'ARENA', 'name': 'Arena Bilgisayar'},
  {'symbol': 'ARFYE', 'name': 'Arfin Yatırım'},
  {'symbol': 'ARMGD', 'name': 'Armada Gıda Ticaret ve Sanayi A.Ş.'},
  {'symbol': 'ARMDA', 'name': 'Arma Dış Ticaret'},
  {'symbol': 'ARMYO', 'name': 'Arma GYO'},
  {'symbol': 'ARSEL', 'name': 'Arsel GYO'},
  {'symbol': 'ARSUZ', 'name': 'Arsuz Gıda'},
  {'symbol': 'ARTIY', 'name': 'Artı Yatırım'},
  {'symbol': 'ARTIM', 'name': 'Artım Gıda'},
  {'symbol': 'ARTIY', 'name': 'Artı Yatırım Holding A.Ş.'},
  {'symbol': 'ARZUM', 'name': 'Arzum Elektrikli Ev Aletleri'},
  {'symbol': 'ARSAN', 'name': 'Arsan Tekstil'},
  {'symbol': 'ARTMS', 'name': 'Artemis Halı A.Ş.'},
  {'symbol': 'ASBTR', 'name': 'Aselsan Bilişim Teknolojileri A.Ş.'},
  {'symbol': 'ASELS', 'name': 'Aselsan'},
  {'symbol': 'ASGYO', 'name': 'Asce GYO'},
  {'symbol': 'ASTOR', 'name': 'Astor Enerji'},
  {'symbol': 'ASUZU', 'name': 'Anadolu Isuzu'},
  {'symbol': 'ATAGY', 'name': 'Ata GYO'},
  {'symbol': 'ATAKP', 'name': 'Atakaş Holding'},
  {'symbol': 'ATATP', 'name': 'Ata Tarım'},
  {'symbol': 'ATATR', 'name': 'Ata Turizm'},
  {'symbol': 'ATEKS', 'name': 'Akın Tekstil'},
  {'symbol': 'ATLAS', 'name': 'Atlas Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'ATSYH', 'name': 'Atlantis Yatırım Holding A.Ş.'},
  {'symbol': 'AVGYO', 'name': 'Avrasya GYO'},
  {'symbol': 'AVHOL', 'name': 'Avrasya Holding'},
  {'symbol': 'AVOD', 'name': 'A.V.O.D Kurutulmuş Gıda'},
  {'symbol': 'AVPGY', 'name': 'Avicenna GYO'},
  {'symbol': 'AVTUR', 'name': 'Avrasya Petrol ve Turistik Tesisler Yatırımlar A.Ş.'},
  {'symbol': 'AYCES', 'name': 'Altınyunus Çeşme'},
  {'symbol': 'AYDEM', 'name': 'Aydem Enerji'},
  {'symbol': 'AYEN', 'name': 'Aydem Yenilenebilir Enerji'},
  {'symbol': 'AYES', 'name': 'Ayes Çelik Hasır ve Çit Sanayi A.Ş.'},
  {'symbol': 'AYGAZ', 'name': 'Aygaz'},
  {'symbol': 'ARZUM', 'name': 'Arzum Elektrikli Ev Aletleri'},
  {'symbol': 'ASELS', 'name': 'Aselsan'},
  {'symbol': 'ASGYO', 'name': 'Aslancık GYO'},
  {'symbol': 'ASTOR', 'name': 'Astor Enerji'},
  {'symbol': 'ASUZU', 'name': 'Anadolu Isuzu'},
  {'symbol': 'ATAGY', 'name': 'Ata GYO'},
  {'symbol': 'ATAKP', 'name': 'Atakaş Holding'},
  {'symbol': 'ATATP', 'name': 'Ata Tarım'},
  {'symbol': 'ATATR', 'name': 'Ata Turizm'},
  {'symbol': 'ATEKS', 'name': 'Akın Tekstil'},
  {'symbol': 'ATLAS', 'name': 'Atlas Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'ATSYH', 'name': 'Atlantis Yatırım Holding A.Ş.'},
  {'symbol': 'AVGYO', 'name': 'Avrasya GYO'},
  {'symbol': 'AVHOL', 'name': 'Avrasya Holding'},
  {'symbol': 'AVOD', 'name': 'A.V.O.D Kurutulmuş Gıda'},
  {'symbol': 'AVPGY', 'name': 'Avicenna GYO'},
  {'symbol': 'AVTUR', 'name': 'Avrasya Petrol ve Turistik Tesisler Yatırımlar A.Ş.'},
  {'symbol': 'AYCES', 'name': 'Altınyunus Çeşme'},
  {'symbol': 'AYDEM', 'name': 'Aydem Enerji'},
  {'symbol': 'AYEN', 'name': 'Aydem Yenilenebilir Enerji'},
  {'symbol': 'AYES', 'name': 'Ayes Çelik Hasır ve Çit Sanayi A.Ş.'},
  {'symbol': 'AYGAZ', 'name': 'Aygaz'},
  {'symbol': 'AZTEK', 'name': 'Aztek'},
  {'symbol': 'BAGFS', 'name': 'Bagfaş Bandırma Gübre'},
  {'symbol': 'BAHKM', 'name': 'Bahçeşehir Koleji'},
  {'symbol': 'BAKAB', 'name': 'Bak Ambalaj Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BALAT', 'name': 'Balatacılar Balatacılık Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BALSU', 'name': 'Balsu Gıda'},
  {'symbol': 'BANVT', 'name': 'Banvit'},
  {'symbol': 'BARMA', 'name': 'Barhane Holding'},
  {'symbol': 'BASCM', 'name': 'Baştaş Başkent Çimento Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BASGZ', 'name': 'Baştaş Başkent'},
  {'symbol': 'BAYRK', 'name': 'Bayrak'},
  {'symbol': 'BEGYO', 'name': 'Beka GYO'},
  {'symbol': 'BERA', 'name': 'Bera Holding'},
  {'symbol': 'BESLR', 'name': 'Beslerbaşı'},
  {'symbol': 'BESTE', 'name': 'Beste Gıda'},
  {'symbol': 'BETAE', 'name': 'Beta Enerji ve Teknoloji A.Ş.'},
  {'symbol': 'BEWEN', 'name': 'Bewen Enerji'},
  {'symbol': 'BEYAZ', 'name': 'Beyaz Filo'},
  {'symbol': 'BFREN', 'name': 'Bosch Fren'},
  {'symbol': 'BIENY', 'name': 'Bien Yapı'},
  {'symbol': 'BIGCH', 'name': 'Big Chef'},
  {'symbol': 'BIGEN', 'name': 'Biogenik'},
  {'symbol': 'BIGTK', 'name': 'Big Teknoloji'},
  {'symbol': 'BIMAS', 'name': 'BİM Mağazalar'},
  {'symbol': 'BINBN', 'name': 'Binbirbuçuk'},
  {'symbol': 'BINHO', 'name': 'Bin Holding'},
  {'symbol': 'BIOEN', 'name': 'Bioenerji'},
  {'symbol': 'BIZIM', 'name': 'Bizim Toptan Satış Mağazaları A.Ş.'},
  {'symbol': 'BJKAS', 'name': 'Beşiktaş Futbol Yatırımları'},
  {'symbol': 'BLCYT', 'name': 'Bilici Yatırım'},
  {'symbol': 'BLUME', 'name': 'Blume'},
  {'symbol': 'BMSCH', 'name': 'BMS Çelik'},
  {'symbol': 'BMSTL', 'name': 'BMS Lojistik'},
  {'symbol': 'BNTAS', 'name': 'Bantaş'},
  {'symbol': 'BOBET', 'name': 'Boğaziçi Beton'},
  {'symbol': 'BORLS', 'name': 'Borluş'},
  {'symbol': 'BORSK', 'name': 'Borsuk Kağıt'},
  {'symbol': 'BOSSA', 'name': 'Bossa Ticaret'},
  {'symbol': 'BRISA', 'name': 'Brisa Bridgestone'},
  {'symbol': 'BRKSN', 'name': 'Berkosan Yalıtım ve Tecrit Maddeleri Üretim ve Ticaret A.Ş.'},
  {'symbol': 'BRKVY', 'name': 'Berkay Yatırım'},
  {'symbol': 'BRLSM', 'name': 'Birleşim Mühendislik'},
  {'symbol': 'BRMEN', 'name': 'Birlik Mensucat Ticaret ve Sanayi İşletmesi A.Ş.'},
  {'symbol': 'BRSAN', 'name': 'Borçelik Çelik'},
  {'symbol': 'BRYAT', 'name': 'Burç Yatırım'},
  {'symbol': 'BSOKE', 'name': 'Batı Söke Çimento'},
  {'symbol': 'BTCIM', 'name': 'Batıçim Batı Anadolu'},
  {'symbol': 'BUCIM', 'name': 'Bursa Çimento'},
  {'symbol': 'BULGS', 'name': 'Bulgurlu'},
  {'symbol': 'BURCE', 'name': 'Burçelik'},
  {'symbol': 'BURVA', 'name': 'Burçelik Vana Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'BVSAN', 'name': 'Birleşik Vagon'},
  {'symbol': 'BYDNR', 'name': 'Baydöner Restoranları A.Ş.'},
  {'symbol': 'CANTE', 'name': 'Can Tarım'},
  {'symbol': 'CASA', 'name': 'Casa Emtia Petrol Kimyevi ve Türevleri Sanayi Ticaret A.Ş.'},
  {'symbol': 'CATES', 'name': 'Çateks'},
  {'symbol': 'CCOLA', 'name': 'Coca-Cola İçecek'},
  {'symbol': 'CELHA', 'name': 'Çelha'},
  {'symbol': 'CEMAS', 'name': 'Cemaş Döküm'},
  {'symbol': 'CEMTS', 'name': 'Çimentaş'},
  {'symbol': 'CEMZY', 'name': 'Çemzy'},
  {'symbol': 'CEOEM', 'name': 'CEO Event Medya A.Ş.'},
  {'symbol': 'CGCAM', 'name': 'Çayırova Cam'},
  {'symbol': 'CIMSA', 'name': 'Çimsa Çimento'},
  {'symbol': 'CLEBI', 'name': 'Çelebi Hava Hizmetleri'},
  {'symbol': 'CMBTN', 'name': 'Çimbeton'},
  {'symbol': 'CMENT', 'name': 'Çimentaş İzmir Çimento Fabrikası T.A.Ş.'},
  {'symbol': 'CONSE', 'name': 'Consus'},
  {'symbol': 'COSMO', 'name': 'Cosmos Yatırım Holding A.Ş.'},
  {'symbol': 'CRDFA', 'name': 'Creditwest Faktoring A.Ş.'},
  {'symbol': 'CRFSA', 'name': 'Carrefoursa'},
  {'symbol': 'CUSAN', 'name': 'Çuhadaroğlu Metal Sanayi ve Pazarlama A.Ş.'},
  {'symbol': 'CVKMD', 'name': 'CVK Madencilik'},
  {'symbol': 'CWENE', 'name': 'CW Enerji'},
  {'symbol': 'DAGI', 'name': 'Dagi Giyim'},
  {'symbol': 'DAPGM', 'name': 'DAP Gayrimenkul'},
  {'symbol': 'DARDL', 'name': 'Dardanel Önentaş'},
  {'symbol': 'DCTTR', 'name': 'DCT Trading Dış Ticaret A.Ş.'},
  {'symbol': 'DEVA', 'name': 'Deva Holding'},
  {'symbol': 'DGNMO', 'name': 'Doğan Müzik'},
  {'symbol': 'DMSAS', 'name': 'Demisaş Döküm'},
  {'symbol': 'DOAS', 'name': 'Doğuş Otomotiv'},
  {'symbol': 'DOHOL', 'name': 'Doğan Holding'},
  {'symbol': 'DOKTA', 'name': 'Döktaş Dökümcülük Ticaret ve Sanayi A.Ş.'},
  {'symbol': 'DURDO', 'name': 'Durdoğan'},
  {'symbol': 'DYOBY', 'name': 'DYO Boya'},
  {'symbol': 'DZGYO', 'name': 'Deniz GYO'},
  {'symbol': 'DENGE', 'name': 'Denge Holding'},
  {'symbol': 'DERHL', 'name': 'Derici Holding'},
  {'symbol': 'DERIM', 'name': 'Derimod Konfeksiyon Ayakkabı Deri Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'DESA', 'name': 'Desa Deri'},
  {'symbol': 'DESPC', 'name': 'Despec Bilgisayar Pazarlama ve Ticaret A.Ş.'},
  {'symbol': 'DEVA', 'name': 'Deva Holding'},
  {'symbol': 'DGATE', 'name': 'Datagate Bilgisayar'},
  {'symbol': 'DGGYO', 'name': 'Doğuş Gayrimenkul Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'DGNMO', 'name': 'Doğan Müzik'},
  {'symbol': 'DIRIT', 'name': 'Diriteks Diriliş Tekstil Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'DITAS', 'name': 'Ditaş Doğan'},
  {'symbol': 'DMRGD', 'name': 'Demirağ'},
  {'symbol': 'DMSAS', 'name': 'Demisaş Döküm'},
  {'symbol': 'DNISI', 'name': 'Deniz İnşaat'},
  {'symbol': 'DOAS', 'name': 'Doğuş Otomotiv'},
  {'symbol': 'DOCO', 'name': 'Doğan Şirketler'},
  {'symbol': 'DOFER', 'name': 'Doğan Fermantasyon'},
  {'symbol': 'DOFRB', 'name': 'Doğan Fren'},
  {'symbol': 'DOGUB', 'name': 'Doğuşan Boru Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'DOHOL', 'name': 'Doğan Holding'},
  {'symbol': 'DOKTA', 'name': 'Döktaş Dökümcülük Ticaret ve Sanayi A.Ş.'},
  {'symbol': 'DSTKF', 'name': 'Destek Faktoring A.Ş.'},
  {'symbol': 'DUNYH', 'name': 'Dünya Holding'},
  {'symbol': 'DURDO', 'name': 'Durdoğan'},
  {'symbol': 'DURKN', 'name': 'Dürkanlı'},
  {'symbol': 'DYOBY', 'name': 'DYO Boya'},
  {'symbol': 'DZGYO', 'name': 'Deniz GYO'},
  {'symbol': 'EBEBK', 'name': 'Ebe Bekleme'},
  {'symbol': 'ECILC', 'name': 'Eczacıbaşı İlaç'},
  {'symbol': 'ECOGR', 'name': 'Ekohisse'},
  {'symbol': 'ECZYT', 'name': 'Eczacıbaşı Yatırım'},
  {'symbol': 'EDATA', 'name': 'E-Data Teknoloji'},
  {'symbol': 'EDIP', 'name': 'Edip İplik'},
  {'symbol': 'EFOR', 'name': 'Efor Enerji'},
  {'symbol': 'EGEEN', 'name': 'Ege Endüstri'},
  {'symbol': 'EGEGY', 'name': 'Ege Gübre'},
  {'symbol': 'EGEPO', 'name': 'Ege Profil'},
  {'symbol': 'EGGUB', 'name': 'Ege Gübre Sanayi'},
  {'symbol': 'EGPRO', 'name': 'EG Pro'},
  {'symbol': 'EGSER', 'name': 'Ege Seramik Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'EKDMR', 'name': 'Ereğli Köyü Demir'},
  {'symbol': 'EKGYO', 'name': 'Emlak Konut GYO'},
  {'symbol': 'EKIM', 'name': 'Ekim Turizm'},
  {'symbol': 'EKIZ', 'name': 'Ekiz Kimya Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'EKOS', 'name': 'Ekos Holding'},
  {'symbol': 'EKSUN', 'name': 'Eksun Gıda'},
  {'symbol': 'ELITE', 'name': 'Elite Naturel'},
  {'symbol': 'EMKEL', 'name': 'Emkel Elektrik'},
  {'symbol': 'EMNIS', 'name': 'Eminiş Ambalaj Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'EMPAE', 'name': 'Empae'},
  {'symbol': 'ENDAE', 'name': 'Enda Enerji'},
  {'symbol': 'ENERY', 'name': 'Enerya Enerji'},
  {'symbol': 'ENJSA', 'name': 'Enerjisa Enerji'},
  {'symbol': 'ENKAI', 'name': 'Enka İnşaat'},
  {'symbol': 'ENPRA', 'name': 'Enerjisa Enerji A.Ş. Paya Dayalı Rüçhan Hakkı'},
  {'symbol': 'ENSRI', 'name': 'Ensari'},
  {'symbol': 'ENTRA', 'name': 'Entra Enerji'},
  {'symbol': 'EPLAS', 'name': 'Egeplast'},
  {'symbol': 'ERBOS', 'name': 'Erbosan Erciyas Boru Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'ERCB', 'name': 'Erceb'},
  {'symbol': 'EREGL', 'name': 'Ereğli Demir Çelik'},
  {'symbol': 'ERSU', 'name': 'Ersu Meyve ve Gıda Sanayi A.Ş.'},
  {'symbol': 'ESCAR', 'name': 'Escort Teknoloji'},
  {'symbol': 'ESCOM', 'name': 'Escort'},
  {'symbol': 'ESEN', 'name': 'Esen'},
  {'symbol': 'ETILR', 'name': 'Etiler Gıda'},
  {'symbol': 'ETYAT', 'name': 'Euro Trend Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'EUHOL', 'name': 'Euro Yatırım Holding A.Ş.'},
  {'symbol': 'EUKYO', 'name': 'Euro Kapital Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'EUPWR', 'name': 'EuroPower Enerji'},
  {'symbol': 'EUREN', 'name': 'Eurenco'},
  {'symbol': 'EUYO', 'name': 'Euro Menkul Kıymet Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'EYGYO', 'name': 'Eyüp Sultan GYO'},
  {'symbol': 'FADE', 'name': 'Fade'},
  {'symbol': 'FENER', 'name': 'Fenerbahçe Futbol'},
  {'symbol': 'FLAP', 'name': 'Flap Kongre Toplantı Hizmetleri Otomotiv ve Turizm A.Ş.'},
  {'symbol': 'FMIZP', 'name': 'Fimizpazarlama'},
  {'symbol': 'FONET', 'name': 'Fonet Bilgi Teknolojileri'},
  {'symbol': 'FORMT', 'name': 'Format'},
  {'symbol': 'FORTE', 'name': 'Forte'},
  {'symbol': 'FRIGO', 'name': 'Frigo-Pak Gıda'},
  {'symbol': 'FRMPL', 'name': 'Fortemple'},
  {'symbol': 'FROTO', 'name': 'Ford Otosan'},
  {'symbol': 'FZLGY', 'name': 'Fazıl GYO'},
  {'symbol': 'GARAN', 'name': 'Garanti BBVA'},
  {'symbol': 'GARFA', 'name': 'Garanti Faktoring'},
  {'symbol': 'GATEG', 'name': 'Gate Elektronik Teknolojileri A.Ş.'},
  {'symbol': 'GEDIK', 'name': 'Gedik Yatırım'},
  {'symbol': 'GEDZA', 'name': 'Gedik Otomotiv'},
  {'symbol': 'GENIL', 'name': 'Genilmas'},
  {'symbol': 'GENKM', 'name': 'Genkima'},
  {'symbol': 'GENTS', 'name': 'Gents'},
  {'symbol': 'GEREL', 'name': 'Gerelsan'},
  {'symbol': 'GESAN', 'name': 'Gesan'},
  {'symbol': 'GIPTA', 'name': 'Gipta'},
  {'symbol': 'GLBMD', 'name': 'Global Menkul Değerler A.Ş.'},
  {'symbol': 'GLCVY', 'name': 'Galata Cavy'},
  {'symbol': 'GLDTR', 'name': 'QNB Portföy Altın Borsa Yatırım Fonu'},
  {'symbol': 'GLRMK', 'name': 'Güler Yatırım'},
  {'symbol': 'GLRYH', 'name': 'Güler Holding'},
  {'symbol': 'GLYHO', 'name': 'Global Yatırım Holding'},
  {'symbol': 'GMSTR', 'name': 'QNB Portföy Gümüş Borsa Yatırım Fonu'},
  {'symbol': 'GMTAS', 'name': 'Gümüştaş'},
  {'symbol': 'GOKNR', 'name': 'Göknur Holding'},
  {'symbol': 'GOLDA', 'name': 'Golda Gıda'},
  {'symbol': 'GOLTS', 'name': 'Göltas Göller'},
  {'symbol': 'GOODY', 'name': 'Goodyear'},
  {'symbol': 'GOZDE', 'name': 'Gözde Girişim'},
  {'symbol': 'GRNYO', 'name': 'Garanti Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'GRSEL', 'name': 'Gursel Turizm'},
  {'symbol': 'GRTHO', 'name': 'Greka Holding'},
  {'symbol': 'GSDDE', 'name': 'GSD Denizcilik Gayrimenkul Geliştirme A.Ş. Rüçhan Hakkı'},
  {'symbol': 'GSDHO', 'name': 'GSD Holding'},
  {'symbol': 'GSRAY', 'name': 'Galatasaray Sportif'},
  {'symbol': 'GUBRF', 'name': 'Gübre Fabrikaları'},
  {'symbol': 'GUNDG', 'name': 'Gündoğdu Holding'},
  {'symbol': 'GWIND', 'name': 'Güneş Wind'},
  {'symbol': 'GZNMI', 'name': 'Gaziantep'},
  {'symbol': 'HALKB', 'name': 'Halkbank'},
  {'symbol': 'HALKS', 'name': 'Halkbank Kısa Vadeli Kira Sertifikası Katılım Fonu'},
  {'symbol': 'HATEK', 'name': 'Hateks Hatay'},
  {'symbol': 'HATSN', 'name': 'Hatsan'},
  {'symbol': 'HDFGS', 'name': 'Hedef Girişim'},
  {'symbol': 'HEDEF', 'name': 'Hedef Holding'},
  {'symbol': 'HEKTS', 'name': 'Hektaş'},
  {'symbol': 'HKTM', 'name': 'Hektaş Teknoloji'},
  {'symbol': 'HLGYO', 'name': 'Halk GYO'},
  {'symbol': 'HOROZ', 'name': 'Horoz Lojistik'},
  {'symbol': 'HRKET', 'name': 'Hareket'},
  {'symbol': 'HTTBT', 'name': 'Hattat Holding'},
  {'symbol': 'HUBVC', 'name': 'Hub Girişim Sermayesi Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'HUNER', 'name': 'Hüner'},
  {'symbol': 'HURGZ', 'name': 'Hürriyet Gazetecilik'},
  {'symbol': 'ICBCT', 'name': 'İç Beton'},
  {'symbol': 'ICUGS', 'name': 'ICU Girişim Sermayesi Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'IDGYO', 'name': 'İdealist Gayrimenkul Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'IEYHO', 'name': 'İEYHO'},
  {'symbol': 'IHAAS', 'name': 'İhlas Finans'},
  {'symbol': 'IHEVA', 'name': 'İhlas Ev Aletleri İmalat Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'IHGZT', 'name': 'İhlas Gazetecilik'},
  {'symbol': 'IHLAS', 'name': 'İhlas Holding'},
  {'symbol': 'IHLGM', 'name': 'İhlas Gayrimenkul'},
  {'symbol': 'IHYAY', 'name': 'İhlas Yayın Holding A.Ş.'},
  {'symbol': 'IMASM', 'name': 'İmas Motor'},
  {'symbol': 'INDES', 'name': 'İndeks Bilgisayar'},
  {'symbol': 'INFO', 'name': 'İnfo Yatırım'},
  {'symbol': 'INGRM', 'name': 'İngram Micro'},
  {'symbol': 'INTEK', 'name': 'İntek Bilgi İşlem Teknolojileri A.Ş.'},
  {'symbol': 'INTEM', 'name': 'İntem'},
  {'symbol': 'INVEO', 'name': 'İnveo Yatırım'},
  {'symbol': 'INVES', 'name': 'İnves Bilgisayar'},
  {'symbol': 'ISATR', 'name': 'İş Bankası A Grubu'},
  {'symbol': 'ISBIR', 'name': 'İşbir Holding A.Ş.'},
  {'symbol': 'ISBTR', 'name': 'İş Bankası B Grubu'},
  {'symbol': 'ISCTR', 'name': 'İş Bankası C'},
  {'symbol': 'ISDMR', 'name': 'İskenderun Demir'},
  {'symbol': 'ISFIN', 'name': 'İş Finansal Kiralama'},
  {'symbol': 'ISGLK', 'name': 'İş Girişim Sermayesi Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'ISGSY', 'name': 'İş Girişim Sermayesi'},
  {'symbol': 'ISGYO', 'name': 'İş GYO'},
  {'symbol': 'ISIST', 'name': 'İşbir Sentetik Dokuma Sanayi A.Ş.'},
  {'symbol': 'ISKPL', 'name': 'İskiplik'},
  {'symbol': 'ISMEN', 'name': 'İş Yatırım Menkul'},
  {'symbol': 'ISSEN', 'name': 'İşbir Sentetik Dokuma Sanayi A.Ş.'},
  {'symbol': 'ISVEA', 'name': 'İsvea Seramik'},
  {'symbol': 'ISYAT', 'name': 'İş Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'IZENR', 'name': 'İzdemir Enerji'},
  {'symbol': 'IZFAS', 'name': 'İzmir Fırça'},
  {'symbol': 'IZINV', 'name': 'İz Yatırım Holding A.Ş.'},
  {'symbol': 'IZMDC', 'name': 'İzmirim Demir Çelik'},
  {'symbol': 'JANTS', 'name': 'Jantsa Jant'},
  {'symbol': 'KAPLM', 'name': 'Kaplama'},
  {'symbol': 'KARCL', 'name': 'Kardemir Çelik'},
  {'symbol': 'KAREL', 'name': 'Karel Elektronik'},
  {'symbol': 'KARSN', 'name': 'Karsan Otomotiv'},
  {'symbol': 'KARTN', 'name': 'Kartonsan'},
  {'symbol': 'KATMR', 'name': 'Katmerciler'},
  {'symbol': 'KAYSE', 'name': 'Kayseri Şeker'},
  {'symbol': 'KBORU', 'name': 'Kayabaşı Boru'},
  {'symbol': 'KCAER', 'name': 'Koca Enerji'},
  {'symbol': 'KCHOL', 'name': 'Koç Holding'},
  {'symbol': 'KENT', 'name': 'Kent Gıda Maddeleri Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'KERVN', 'name': 'Kervansaray Yatırım Holding A.Ş.'},
  {'symbol': 'KFEIN', 'name': 'Kafe İnternational'},
  {'symbol': 'KGYO', 'name': 'Kırklareli GYO'},
  {'symbol': 'KIMMR', 'name': 'Kimmer'},
  {'symbol': 'KLGYO', 'name': 'Kiler GYO'},
  {'symbol': 'KLKIM', 'name': 'Klik Kimya'},
  {'symbol': 'KLMSN', 'name': 'Klimasan Klima'},
  {'symbol': 'KLNMA', 'name': 'Türkiye Kalkınma ve Yatırım Bankası A.Ş.'},
  {'symbol': 'KLRHO', 'name': 'Kiler Holding'},
  {'symbol': 'KLSER', 'name': 'Kliser'},
  {'symbol': 'KLSYN', 'name': 'Kılıç Şarap'},
  {'symbol': 'KLYPV', 'name': 'Kalyon PV'},
  {'symbol': 'KMPUR', 'name': 'Kombassan Holding'},
  {'symbol': 'KNFRT', 'name': 'Konfirst'},
  {'symbol': 'KOCMT', 'name': 'Koç Enerji'},
  {'symbol': 'KONKA', 'name': 'Konkar Petrol'},
  {'symbol': 'KONTR', 'name': 'Kontrat'},
  {'symbol': 'KONYA', 'name': 'Konya Çimento'},
  {'symbol': 'KOPOL', 'name': 'Kopol'},
  {'symbol': 'KORDS', 'name': 'Kordsa'},
  {'symbol': 'KOTON', 'name': 'Koton'},
  {'symbol': 'KRDMA', 'name': 'Kardemir Karabük Demir Çelik Sanayi ve Ticaret A.Ş. (A)'},
  {'symbol': 'KRDMB', 'name': 'Kardemir Karabük Demir Çelik Sanayi ve Ticaret A.Ş. (B)'},
  {'symbol': 'KRDMD', 'name': 'Kardemir D'},
  {'symbol': 'KRGYO', 'name': 'Karşıyaka GYO'},
  {'symbol': 'KRONT', 'name': 'Kron Telekomünikasyon'},
  {'symbol': 'KRPLS', 'name': 'Karplus'},
  {'symbol': 'KRSTL', 'name': 'Kristal Kola'},
  {'symbol': 'KRTEK', 'name': 'Karsu Tekstil Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'KRVGD', 'name': 'Kervan Gıda'},
  {'symbol': 'KSTUR', 'name': 'Kuştur Kuşadası Turizm Endüstrisi A.Ş.'},
  {'symbol': 'KTLEV', 'name': 'Katılım Emeklilik'},
  {'symbol': 'KTSKR', 'name': 'Konya Tatko Şeker'},
  {'symbol': 'KUTPO', 'name': 'Kümaş Manyezit'},
  {'symbol': 'KUVVA', 'name': 'Kuvva Gıda Ticaret ve Sanayi Yatırımları A.Ş.'},
  {'symbol': 'KUYAS', 'name': 'Kuyas'},
  {'symbol': 'KZBGY', 'name': 'Kuzey Bolu'},
  {'symbol': 'KZGYO', 'name': 'Kuzey GYO'},
  {'symbol': 'LIDER', 'name': 'Lider Faktoring'},
  {'symbol': 'LIDFA', 'name': 'Lider Faktoring A'},
  {'symbol': 'LILAK', 'name': 'Lilak'},
  {'symbol': 'LINK', 'name': 'Link Bilgisayar'},
  {'symbol': 'LKMNH', 'name': 'Lokman Hekim'},
  {'symbol': 'LMKDC', 'name': 'Limak Doğalgaz'},
  {'symbol': 'LOGO', 'name': 'Logo Yazılım'},
  {'symbol': 'LRSHO', 'name': 'Larsa Holding'},
  {'symbol': 'LUKSK', 'name': 'Lüks Kadife Ticaret ve Sanayi A.Ş.'},
  {'symbol': 'LXGYO', 'name': 'Lüxtera GYO'},
  {'symbol': 'LYDHO', 'name': 'Lider Holding'},
  {'symbol': 'LYDYE', 'name': 'Lydia Yeşil Enerji Kaynakları A.Ş.'},
  {'symbol': 'MAALT', 'name': 'M.A. Altın'},
  {'symbol': 'MACKO', 'name': 'Macko'},
  {'symbol': 'MAGEN', 'name': 'Magna'},
  {'symbol': 'MAKIM', 'name': 'Makim'},
  {'symbol': 'MAKTK', 'name': 'Mak Teknik'},
  {'symbol': 'MANAS', 'name': 'Manas'},
  {'symbol': 'MARBL', 'name': 'Marbella'},
  {'symbol': 'MARKA', 'name': 'Marka Yatırım'},
  {'symbol': 'MARMR', 'name': 'Marmaris Altınyunus'},
  {'symbol': 'MARTI', 'name': 'Martı Otel'},
  {'symbol': 'MASFN', 'name': 'Masfen Enerji'},
  {'symbol': 'MAVI', 'name': 'Mavi Giyim'},
  {'symbol': 'MCARD', 'name': 'Mastercard'},
  {'symbol': 'MEDTR', 'name': 'Meditera'},
  {'symbol': 'MEGAP', 'name': 'Mega Polietilen Köpük Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'MEGMT', 'name': 'Mega Menkul'},
  {'symbol': 'MEKAG', 'name': 'Meka Gıda'},
  {'symbol': 'MEPET', 'name': 'Mepet Metro Petrol ve Tesisleri Sanayi Ticaret A.Ş.'},
  {'symbol': 'MERCN', 'name': 'Mercan'},
  {'symbol': 'MERIT', 'name': 'Merit Turizm'},
  {'symbol': 'MERKO', 'name': 'Merko Gıda'},
  {'symbol': 'METEN', 'name': 'Metgun Enerji'},
  {'symbol': 'METRO', 'name': 'Metro Ticaret'},
  {'symbol': 'MEYSU', 'name': 'Mey Su'},
  {'symbol': 'MGROS', 'name': 'Migros'},
  {'symbol': 'MHRGY', 'name': 'Mahir GYO'},
  {'symbol': 'MIATK', 'name': 'Mia Teknoloji'},
  {'symbol': 'MMCAS', 'name': 'MMC Sanayi ve Ticari Yatırımlar A.Ş.'},
  {'symbol': 'MNDRS', 'name': 'Menderes Tekstil'},
  {'symbol': 'MNDTR', 'name': 'Meindert'},
  {'symbol': 'MOBTL', 'name': 'Mobil Telekom'},
  {'symbol': 'MOGAN', 'name': 'Mogan'},
  {'symbol': 'MOPAS', 'name': 'Mopaş'},
  {'symbol': 'MPARK', 'name': 'MLP Sağlık'},
  {'symbol': 'MRGYO', 'name': 'Mert GYO'},
  {'symbol': 'MRSHL', 'name': 'Marshall Boya'},
  {'symbol': 'MSGYO', 'name': 'Metropol GYO'},
  {'symbol': 'MTRKS', 'name': 'Metriksel'},
  {'symbol': 'MTRYO', 'name': 'Metro Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'MZHLD', 'name': 'Mazhar Zorlu Holding A.Ş.'},
  {'symbol': 'NATEN', 'name': 'Naturel Enerji'},
  {'symbol': 'NETAS', 'name': 'Netaş Telekomünikasyon'},
  {'symbol': 'NETCD', 'name': 'Netcad'},
  {'symbol': 'NIBAS', 'name': 'Nibas'},
  {'symbol': 'NPTLR', 'name': 'Netaş Pay Rüçhan Hakkı'},
  {'symbol': 'NTGAZ', 'name': 'Naturelgaz'},
  {'symbol': 'NTHOL', 'name': 'Net Holding'},
  {'symbol': 'NUGYO', 'name': 'Nurol GYO'},
  {'symbol': 'NUHCM', 'name': 'Nuh Çimento'},
  {'symbol': 'OBAMS', 'name': 'Obams'},
  {'symbol': 'OBASE', 'name': 'Obase Bilgisayar ve Danışmanlık Hizmetleri Ticaret A.Ş.'},
  {'symbol': 'ODAS', 'name': 'Odaş Elektrik'},
  {'symbol': 'ODINE', 'name': 'Odine'},
  {'symbol': 'OFSYM', 'name': 'Ofis Yönetim'},
  {'symbol': 'ONCSM', 'name': 'Öncü Girişim'},
  {'symbol': 'ONRYT', 'name': 'Onur Rüzgar'},
  {'symbol': 'OPK30', 'name': 'Osmanlı Portföy BIST 30 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'OPT25', 'name': 'Osmanlı Portföy BIST Temettü 25 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'OPTGY', 'name': 'Optimum Yatırım Gayrimenkul Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'OPTLR', 'name': 'Osmanlı Portföy TL Kısa Vadeli Borçlanma Araçları BYF'},
  {'symbol': 'OPX30', 'name': 'Osmanlı Portföy BIST 30 Endeksi Hisse Senedi Yoğun BYF'},
  {'symbol': 'ORCAY', 'name': 'Orçay Ortaköy Çay Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'ORGE', 'name': 'Orge Enerji'},
  {'symbol': 'ORMA', 'name': 'Orma Orman Mahsulleri Entegre Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'ORZAX', 'name': 'Orzaks İlaç'},
  {'symbol': 'OSMEN', 'name': 'Osman'},
  {'symbol': 'OSTIM', 'name': 'OSTİM Endüstriyel'},
  {'symbol': 'OTKAR', 'name': 'Otokar'},
  {'symbol': 'OTTO', 'name': 'Otto'},
  {'symbol': 'OYAKC', 'name': 'Oyak Çimento'},
  {'symbol': 'OYAYO', 'name': 'Oyak Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'OYLUM', 'name': 'Oylum Sınai Yatırımlar A.Ş.'},
  {'symbol': 'OYYAT', 'name': 'Oyak Yatırım'},
  {'symbol': 'OZATD', 'name': 'Özata Denizcilik'},
  {'symbol': 'OZGYO', 'name': 'Özgün GYO'},
  {'symbol': 'OZKGY', 'name': 'Özak GYO'},
  {'symbol': 'OZRDN', 'name': 'Özerden Plastik Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'OZSUB', 'name': 'Özsu Bilişim'},
  {'symbol': 'OZYSR', 'name': 'Özyaşar'},
  {'symbol': 'PAGYO', 'name': 'Pasha GYO'},
  {'symbol': 'PAHOL', 'name': 'Pasha Holding'},
  {'symbol': 'PAMEL', 'name': 'Pamel Yenilenebilir Elektrik Üretim A.Ş.'},
  {'symbol': 'PAPIL', 'name': 'Papilion'},
  {'symbol': 'PARSN', 'name': 'Parsan'},
  {'symbol': 'PASEU', 'name': 'Pasifik'},
  {'symbol': 'PATEK', 'name': 'Patek'},
  {'symbol': 'PCILT', 'name': 'PC İletişim'},
  {'symbol': 'PEKGY', 'name': 'Pek GYO'},
  {'symbol': 'PENGD', 'name': 'Penguengd'},
  {'symbol': 'PENTA', 'name': 'Penta Teknoloji'},
  {'symbol': 'PETKM', 'name': 'Petkim'},
  {'symbol': 'PETUN', 'name': 'Pınar Et'},
  {'symbol': 'PGSUS', 'name': 'Pegasus'},
  {'symbol': 'PINSU', 'name': 'Pınar Su'},
  {'symbol': 'PKART', 'name': 'Plastik Kart'},
  {'symbol': 'PKENT', 'name': 'Petrokent Turizm'},
  {'symbol': 'PLTUR', 'name': 'Poltur'},
  {'symbol': 'PNLSN', 'name': 'Pınar Süt'},
  {'symbol': 'PNSUT', 'name': 'Pınar Süt Mamulleri'},
  {'symbol': 'POLHO', 'name': 'Polisan Holding'},
  {'symbol': 'POLTK', 'name': 'Politeknik'},
  {'symbol': 'PRDGS', 'name': 'Pardus'},
  {'symbol': 'PRKAB', 'name': 'Pimaş Plastik'},
  {'symbol': 'PRKME', 'name': 'Peker'},
  {'symbol': 'PRZMA', 'name': 'Prizma Pres Matbaacılık Yayıncılık Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'PSDTC', 'name': 'Pergamon Status Dış Ticaret A.Ş.'},
  {'symbol': 'PSGYO', 'name': 'Panora GYO'},
  {'symbol': 'QNBFK', 'name': 'QNB Finans Finansal Kiralama A.Ş.'},
  {'symbol': 'QNBTR', 'name': 'QNB Bank A.Ş.'},
  {'symbol': 'QTEMZ', 'name': 'QNB Portföy Temiz Enerji Değişken BYF'},
  {'symbol': 'QUAGR', 'name': 'Qua Granite'},
  {'symbol': 'QUICK', 'name': 'Quick Sigorta'},
  {'symbol': 'RALYH', 'name': 'Ray Holding'},
  {'symbol': 'RAYSG', 'name': 'Ray Sigorta'},
  {'symbol': 'REEDR', 'name': 'Reedr'},
  {'symbol': 'RGYAS', 'name': 'Reysaş GYO'},
  {'symbol': 'RNPOL', 'name': 'Rainbow Polikarbonat Sanayi Ticaret A.Ş.'},
  {'symbol': 'RODRG', 'name': 'Rodrigo Tekstil Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'RTALB', 'name': 'Rota Liman'},
  {'symbol': 'RUBNS', 'name': 'Rubenis'},
  {'symbol': 'RUZYE', 'name': 'Rüzgar Enerji'},
  {'symbol': 'RYGYO', 'name': 'Reyhan GYO'},
  {'symbol': 'RYSAS', 'name': 'Reysaş Taşımacılık'},
  {'symbol': 'SAFKR', 'name': 'Safkar'},
  {'symbol': 'SAHOL', 'name': 'Sabancı Holding'},
  {'symbol': 'SAMAT', 'name': 'Saray Matbaacılık Kâğıtçılık Kırtasiyecilik Ticaret ve Sanayi A.Ş.'},
  {'symbol': 'SANEL', 'name': 'Sanel Mühendislik Elektrik Taahhüt Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'SANFM', 'name': 'Sanifoam'},
  {'symbol': 'SANKO', 'name': 'Sanko Pazarlama İthalat İhracat A.Ş.'},
  {'symbol': 'SARAE', 'name': 'Sa-Ra Enerji'},
  {'symbol': 'SARKY', 'name': 'Sarkuysan'},
  {'symbol': 'SASA', 'name': 'Sasa Polyester'},
  {'symbol': 'SAYAS', 'name': 'Sayas'},
  {'symbol': 'SDTTR', 'name': 'SDT Uzay ve Savunma Teknolojileri A.Ş.'},
  {'symbol': 'SEALE', 'name': 'Seale'},
  {'symbol': 'SEGMN', 'name': 'Segmen Kardeşler Gıda Uretim ve Ambalaj Sanayi A.Ş.'},
  {'symbol': 'SEGYO', 'name': 'Seğmen GYO'},
  {'symbol': 'SEKFK', 'name': 'Şeker Finansal Kiralama A.Ş.'},
  {'symbol': 'SEKUR', 'name': 'Sekuro Plastik Ambalaj Sanayi A.Ş.'},
  {'symbol': 'SELEC', 'name': 'Selçuk Ecza'},
  {'symbol': 'SELVA', 'name': 'Selva Gıda'},
  {'symbol': 'SERNT', 'name': 'Seranit'},
  {'symbol': 'SEYKM', 'name': 'Seyitler Kimya Sanayi A.Ş.'},
  {'symbol': 'SILVR', 'name': 'Silverline Endüstri ve Ticaret A.Ş.'},
  {'symbol': 'SISE', 'name': 'Şişe Cam'},
  {'symbol': 'SKBNK', 'name': 'Şekerbank'},
  {'symbol': 'SKTAS', 'name': 'Söktaş Tekstil'},
  {'symbol': 'SKYLP', 'name': 'Skyalp Finansal Teknolojiler ve Danışmanlık A.Ş.'},
  {'symbol': 'SKYMD', 'name': 'Sky Maden'},
  {'symbol': 'SMART', 'name': 'Smart Güneş'},
  {'symbol': 'SMRTG', 'name': 'Smart GYO'},
  {'symbol': 'SMRVA', 'name': 'Samir Sağlık'},
  {'symbol': 'SNGYO', 'name': 'Sinpaş GYO'},
  {'symbol': 'SNICA', 'name': 'Sönica'},
  {'symbol': 'SNPAM', 'name': 'Sönmez Pamuklu Sanayii A.Ş.'},
  {'symbol': 'SODA', 'name': 'Soda Sanayii'},
  {'symbol': 'SODSN', 'name': 'Sodaş Sodyum Sanayii A.Ş.'},
  {'symbol': 'SOHOE', 'name': 'Soho Giyim ve Enerji'},
  {'symbol': 'SOKE', 'name': 'Söke Değirmen'},
  {'symbol': 'SOKM', 'name': 'Şok Marketler'},
  {'symbol': 'SONME', 'name': 'Sönmez Filament Sentetik İplik ve Elyaf Sanayi A.Ş.'},
  {'symbol': 'SRVGY', 'name': 'Süreyya GYO'},
  {'symbol': 'SSAAT', 'name': 'Saat ve Saat'},
  {'symbol': 'SUMAS', 'name': 'Sumaş Suni Tahta ve Mobilya Sanayi A.Ş.'},
  {'symbol': 'SUNTK', 'name': 'Sunteks'},
  {'symbol': 'SURGY', 'name': 'Sur Yapı GYO'},
  {'symbol': 'SUWEN', 'name': 'Süwen İç Giyim'},
  {'symbol': 'SVGYO', 'name': 'Sev GYO'},
  {'symbol': 'TABGD', 'name': 'TAB Gıda'},
  {'symbol': 'TARKM', 'name': 'Tarkim'},
  {'symbol': 'TATEN', 'name': 'Tatlıpınar Enerji'},
  {'symbol': 'TATGD', 'name': 'Tat Gıda'},
  {'symbol': 'TAVHL', 'name': 'TAV Havalimanları'},
  {'symbol': 'TBORG', 'name': 'Türk Tuborg'},
  {'symbol': 'TCELL', 'name': 'Turkcell'},
  {'symbol': 'TCKRC', 'name': 'Türk Kırmızı'},
  {'symbol': 'TDGYO', 'name': 'Trend Gayrimenkul Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'TEHOL', 'name': 'Tekno Holding'},
  {'symbol': 'TEKTU', 'name': 'Tek-T Uçak'},
  {'symbol': 'TERA', 'name': 'Tera Yatırım'},
  {'symbol': 'TEZOL', 'name': 'Tezol'},
  {'symbol': 'TGSAS', 'name': 'Türk Gaz'},
  {'symbol': 'THYAO', 'name': 'Türk Hava Yolları'},
  {'symbol': 'TKFEN', 'name': 'Tekfen Holding'},
  {'symbol': 'TKNSA', 'name': 'Teknosa'},
  {'symbol': 'TLMAN', 'name': 'Tailormade'},
  {'symbol': 'TMPOL', 'name': 'Temapol Polimer'},
  {'symbol': 'TMSN', 'name': 'Tamsan'},
  {'symbol': 'TNZTP', 'name': 'Tanı'},
  {'symbol': 'TOASO', 'name': 'Tofaş Oto. Fab.'},
  {'symbol': 'TRALT', 'name': 'Tür Altın'},
  {'symbol': 'TRCAS', 'name': 'Tür Çelik'},
  {'symbol': 'TRENJ', 'name': 'Türen Enerji'},
  {'symbol': 'TRGYO', 'name': 'Torunlar GYO'},
  {'symbol': 'TRHOL', 'name': 'Turkish Yatırım Holding A.Ş.'},
  {'symbol': 'TRILC', 'name': 'Türk İlaç ve Serum Sanayi A.Ş.'},
  {'symbol': 'TRMET', 'name': 'Tür Metal'},
  {'symbol': 'TSGYO', 'name': 'TSKB Gayrimenkul Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'TSKB', 'name': 'Türkiye Sınai Kalkınma Bankası A.Ş.'},
  {'symbol': 'TSPOR', 'name': 'Trabzonspor'},
  {'symbol': 'TTKOM', 'name': 'Türk Telekom'},
  {'symbol': 'TTRAK', 'name': 'Türk Traktör'},
  {'symbol': 'TUCLK', 'name': 'Tuçkağıt'},
  {'symbol': 'TUKAS', 'name': 'Tukaş'},
  {'symbol': 'TUPRS', 'name': 'Tüpraş'},
  {'symbol': 'TUREX', 'name': 'Tureks Turizm'},
  {'symbol': 'TURGG', 'name': 'Türker Proje'},
  {'symbol': 'TURSG', 'name': 'Türkiye Sigorta'},
  {'symbol': 'UCAYM', 'name': 'Uçak Servisi'},
  {'symbol': 'UFUK', 'name': 'Ufuk Yatırım Yönetim ve Gayrimenkul A.Ş.'},
  {'symbol': 'ULAS', 'name': 'Ulaşlar Turizm Yatırımları ve Dayanıklı Tüketim Malları Ticaret A.Ş.'},
  {'symbol': 'ULKER', 'name': 'Ülker Bisküvi'},
  {'symbol': 'ULUFA', 'name': 'Ulusoy Filo'},
  {'symbol': 'ULUSE', 'name': 'Ulusoy Elektrik'},
  {'symbol': 'ULUUN', 'name': 'Ulusoy Un'},
  {'symbol': 'UNLU', 'name': 'Ünlü Yatırım'},
  {'symbol': 'USAK', 'name': 'Uşak Seramik'},
  {'symbol': 'USDTR', 'name': 'QNB Portföy Dolar Borsa Yatırım Fonu'},
  {'symbol': 'VAKBN', 'name': 'Vakıfbank'},
  {'symbol': 'VAKFA', 'name': 'Vakıf Finansal Kiralama'},
  {'symbol': 'VAKFN', 'name': 'Vakıf Finans'},
  {'symbol': 'VAKKO', 'name': 'Vakko Tekstil'},
  {'symbol': 'VANGD', 'name': 'Vanet Gıda Sanayi İç ve Dış Ticaret A.Ş.'},
  {'symbol': 'VBTYZ', 'name': 'Vbt Yazılım'},
  {'symbol': 'VERTU', 'name': 'Vertu'},
  {'symbol': 'VERUS', 'name': 'Verus'},
  {'symbol': 'VESBE', 'name': 'Vestel Beyaz Eşya'},
  {'symbol': 'VESTL', 'name': 'Vestel Elektronik'},
  {'symbol': 'VKFYO', 'name': 'Vakıf Menkul Kıymet Yatırım Ortaklığı A.Ş.'},
  {'symbol': 'VKGYO', 'name': 'Vakıf GYO'},
  {'symbol': 'VKING', 'name': 'Viking Kağıt ve Selüloz A.Ş.'},
  {'symbol': 'VRGYO', 'name': 'Varlık GYO'},
  {'symbol': 'VSNMD', 'name': 'Vosmer'},
  {'symbol': 'X030S', 'name': 'X030S'},
  {'symbol': 'X100S', 'name': 'X100S'},
  {'symbol': 'XBANA', 'name': 'XBANA'},
  {'symbol': 'XBANK', 'name': 'XBANK'},
  {'symbol': 'XBLSM', 'name': 'XBLSM'},
  {'symbol': 'XELKT', 'name': 'XELKT'},
  {'symbol': 'XFINK', 'name': 'XFINK'},
  {'symbol': 'XGIDA', 'name': 'XGIDA'},
  {'symbol': 'XGMYO', 'name': 'XGMYO'},
  {'symbol': 'XHARZ', 'name': 'XHARZ'},
  {'symbol': 'XHOLD', 'name': 'XHOLD'},
  {'symbol': 'XILTM', 'name': 'XILTM'},
  {'symbol': 'XINSA', 'name': 'XINSA'},
  {'symbol': 'XKAGT', 'name': 'XKAGT'},
  {'symbol': 'XKMYA', 'name': 'XKMYA'},
  {'symbol': 'XKOBI', 'name': 'XKOBI'},
  {'symbol': 'XKURY', 'name': 'XKURY'},
  {'symbol': 'XMADN', 'name': 'XMADN'},
  {'symbol': 'XMANA', 'name': 'XMANA'},
  {'symbol': 'XMESY', 'name': 'XMESY'},
  {'symbol': 'XSADA', 'name': 'XSADA'},
  {'symbol': 'XSANK', 'name': 'XSANK'},
  {'symbol': 'XSANT', 'name': 'XSANT'},
  {'symbol': 'XSBAL', 'name': 'XSBAL'},
  {'symbol': 'XSBUR', 'name': 'XSBUR'},
  {'symbol': 'XSDNZ', 'name': 'XSDNZ'},
  {'symbol': 'XSGRT', 'name': 'XSGRT'},
  {'symbol': 'XSIST', 'name': 'XSIST'},
  {'symbol': 'XSIZM', 'name': 'XSIZM'},
  {'symbol': 'XSKAY', 'name': 'XSKAY'},
  {'symbol': 'XSKOC', 'name': 'XSKOC'},
  {'symbol': 'XSKON', 'name': 'XSKON'},
  {'symbol': 'XSPOR', 'name': 'XSPOR'},
  {'symbol': 'XSTKR', 'name': 'XSTKR'},
  {'symbol': 'XTAST', 'name': 'XTAST'},
  {'symbol': 'XTCRT', 'name': 'XTCRT'},
  {'symbol': 'XTEKS', 'name': 'XTEKS'},
  {'symbol': 'XTM25', 'name': 'XTM25'},
  {'symbol': 'XTMTU', 'name': 'XTMTU'},
  {'symbol': 'XTRZM', 'name': 'XTRZM'},
  {'symbol': 'XTUMY', 'name': 'XTUMY'},
  {'symbol': 'XU030', 'name': 'XU030'},
  {'symbol': 'XU050', 'name': 'XU050'},
  {'symbol': 'XU100', 'name': 'XU100'},
  {'symbol': 'XUHIZ', 'name': 'XUHIZ'},
  {'symbol': 'XULAS', 'name': 'XULAS'},
  {'symbol': 'XUMAL', 'name': 'XUMAL'},
  {'symbol': 'XUSIN', 'name': 'XUSIN'},
  {'symbol': 'XUSRD', 'name': 'XUSRD'},
  {'symbol': 'XUTEK', 'name': 'XUTEK'},
  {'symbol': 'XUTUM', 'name': 'XUTUM'},
  {'symbol': 'XYLDZ', 'name': 'XYLDZ'},
  {'symbol': 'XYORT', 'name': 'XYORT'},
  {'symbol': 'XYUZO', 'name': 'XYUZO'},
  {'symbol': 'YAPRK', 'name': 'Yaprak'},
  {'symbol': 'YATAS', 'name': 'Yataş'},
  {'symbol': 'YAYLA', 'name': 'Yayla Agro'},
  {'symbol': 'YBTAS', 'name': 'Yibitaş Yozgat İşçi Birliği İnşaat Malzemeleri Ticaret ve Sanayi A.Ş.'},
  {'symbol': 'YEOTK', 'name': 'Yeotk'},
  {'symbol': 'YESIL', 'name': 'Yeşil Yatırım'},
  {'symbol': 'YGGYO', 'name': 'Yeni Gimat GYO'},
  {'symbol': 'YIGIT', 'name': 'Yiğit Aksesuar'},
  {'symbol': 'YKBNK', 'name': 'Yapı Kredi Bankası'},
  {'symbol': 'YKSLN', 'name': 'Yükselen Çelik'},
  {'symbol': 'YONGA', 'name': 'Yonga Mobilya Sanayi ve Ticaret A.Ş.'},
  {'symbol': 'YUNSA', 'name': 'Yünsa'},
  {'symbol': 'YYAPI', 'name': 'Yeşil Yapı Endüstrisi A.Ş.'},
  {'symbol': 'YYLGD', 'name': 'Yayla Gıda'},
  {'symbol': 'Z30EA', 'name': 'Z30EA'},
  {'symbol': 'Z30KE', 'name': 'Z30KE'},
  {'symbol': 'Z30KP', 'name': 'Z30KP'},
  {'symbol': 'ZEDUR', 'name': 'ZEDUR'},
  {'symbol': 'ZELOT', 'name': 'ZELOT'},
  {'symbol': 'ZERGY', 'name': 'Zerya Enerji'},
  {'symbol': 'ZGOLD', 'name': 'ZGOLD'},
  {'symbol': 'ZGYO', 'name': 'Zirve GYO'},
  {'symbol': 'ZOREN', 'name': 'Zorlu Enerji'},
  {'symbol': 'ZPBDL', 'name': 'ZPBDL'},
  {'symbol': 'ZPLIB', 'name': 'ZPLIB'},
  {'symbol': 'ZPT10', 'name': 'ZPT10'},
  {'symbol': 'ZPX30', 'name': 'ZPX30'},
  {'symbol': 'ZRE20', 'name': 'ZRE20'},
  {'symbol': 'ZRGYO', 'name': 'Ziraat GYO'},
  {'symbol': 'ZSR25', 'name': 'ZSR25'},
  {'symbol': 'ZTLRF', 'name': 'ZTLRF'},
  {'symbol': 'ZTLRK', 'name': 'ZTLRK'},
  {'symbol': 'ZTM25', 'name': 'ZTM25'},
];

List<Map<String, String>> kBistStocks = List<Map<String, String>>.from(_baseBistStocks);

void syncBistStocksWithIpoItems(List<IpoItem> ipoItems) {
  final merged = <Map<String, String>>[];
  final seenSymbols = <String>{};

  for (final entry in _baseBistStocks) {
    final symbol = (entry['symbol'] ?? '').toString().toUpperCase();
    if (symbol.isEmpty || seenSymbols.contains(symbol)) continue;
    seenSymbols.add(symbol);
    merged.add(Map<String, String>.from(entry));
  }

  for (final item in ipoItems.where((item) =>
      item.status == IpoStatus.trading && item.symbol.isNotEmpty)) {
    final symbol = item.symbol.toUpperCase();
    if (seenSymbols.contains(symbol)) continue;
    seenSymbols.add(symbol);
    final name = item.companyName.trim().isNotEmpty
        ? item.companyName.trim()
        : symbol;
    merged.add({'symbol': symbol, 'name': name});
  }

  merged.sort((a, b) =>
      (a['symbol'] ?? '').toLowerCase().compareTo((b['symbol'] ?? '').toLowerCase()));
  kBistStocks = merged;
}
