from pathlib import Path

updates = {
    'APBDL': 'Ak Portföy BIST Banka Dışı Likit 10 Endeksi Hisse Senedi Yoğun BYF',
    'APGLD': 'Ak Portföy Altın Katılım Borsa Yatırım Fonu',
    'APLIB': 'Ak Portföy BIST Likit Banka Endeksi Hisse Senedi Yoğun BYF',
    'APMDL': 'Ak Portföy BIST 100 Endeksi Model Portföy Hisse Senedi Yoğun BYF',
    'APX30': 'Ak Portföy BIST 30 Endeksi Hisse Senedi Yoğun BYF',
    'ATLAS': 'Atlas Yatırım Ortaklığı A.Ş.',
    'ATSYH': 'Atlantis Yatırım Holding A.Ş.',
    'AVTUR': 'Avrasya Petrol ve Turistik Tesisler Yatırımlar A.Ş.',
    'AYES': 'Ayes Çelik Hasır ve Çit Sanayi A.Ş.',
    'BAKAB': 'Bak Ambalaj Sanayi ve Ticaret A.Ş.',
    'BALAT': 'Balatacılar Balatacılık Sanayi ve Ticaret A.Ş.',
    'BASCM': 'Baştaş Başkent Çimento Sanayi ve Ticaret A.Ş.',
    'BETAE': 'Beta Enerji ve Teknoloji A.Ş.',
    'BIZIM': 'Bizim Toptan Satış Mağazaları A.Ş.',
    'BRKSN': 'Berkosan Yalıtım ve Tecrit Maddeleri Üretim ve Ticaret A.Ş.',
    'BRMEN': 'Birlik Mensucat Ticaret ve Sanayi İşletmesi A.Ş.',
    'BURVA': 'Burçelik Vana Sanayi ve Ticaret A.Ş.',
    'BYDNR': 'Baydöner Restoranları A.Ş.',
    'CASA': 'Casa Emtia Petrol Kimyevi ve Türevleri Sanayi Ticaret A.Ş.',
    'CEOEM': 'CEO Event Medya A.Ş.',
    'CMENT': 'Çimentaş İzmir Çimento Fabrikası T.A.Ş.',
    'COSMO': 'Cosmos Yatırım Holding A.Ş.',
    'CRDFA': 'Creditwest Faktoring A.Ş.',
    'CUSAN': 'Çuhadaroğlu Metal Sanayi ve Pazarlama A.Ş.',
    'DERIM': 'Derimod Konfeksiyon Ayakkabı Deri Sanayi ve Ticaret A.Ş.',
    'DESPC': 'Despec Bilgisayar Pazarlama ve Ticaret A.Ş.',
    'DGGYO': 'Doğuş Gayrimenkul Yatırım Ortaklığı A.Ş.',
    'DIRIT': 'Diriteks Diriliş Tekstil Sanayi ve Ticaret A.Ş.',
    'DOGUB': 'Doğuşan Boru Sanayi ve Ticaret A.Ş.',
    'DOKTA': 'Döktaş Dökümcülük Ticaret ve Sanayi A.Ş.',
    'DSTKF': 'Destek Faktoring A.Ş.',
    'EGSER': 'Ege Seramik Sanayi ve Ticaret A.Ş.',
    'EKIZ': 'Ekiz Kimya Sanayi ve Ticaret A.Ş.',
    'EMNIS': 'Eminiş Ambalaj Sanayi ve Ticaret A.Ş.',
    'ENPRA': 'Enerjisa Enerji A.Ş. Paya Dayalı Rüçhan Hakkı',
    'ERBOS': 'Erbosan Erciyas Boru Sanayi ve Ticaret A.Ş.',
    'ERSU': 'Ersu Meyve ve Gıda Sanayi A.Ş.',
    'ETYAT': 'Euro Trend Yatırım Ortaklığı A.Ş.',
    'EUHOL': 'Euro Yatırım Holding A.Ş.',
    'EUKYO': 'Euro Kapital Yatırım Ortaklığı A.Ş.',
    'EUYO': 'Euro Menkul Kıymet Yatırım Ortaklığı A.Ş.',
    'FLAP': 'Flap Kongre Toplantı Hizmetleri Otomotiv ve Turizm A.Ş.',
    'GATEG': 'Gate Elektronik Teknolojileri A.Ş.',
    'GLBMD': 'Global Menkul Değerler A.Ş.',
    'GLDTR': 'QNB Portföy Altın Borsa Yatırım Fonu',
    'GMSTR': 'QNB Portföy Gümüş Borsa Yatırım Fonu',
    'GRNYO': 'Garanti Yatırım Ortaklığı A.Ş.',
    'GSDDE': 'GSD Denizcilik Gayrimenkul Geliştirme A.Ş. Rüçhan Hakkı',
    'HALKS': 'Halkbank Kısa Vadeli Kira Sertifikası Katılım Fonu',
    'HUBVC': 'Hub Girişim Sermayesi Yatırım Ortaklığı A.Ş.',
    'ICUGS': 'ICU Girişim Sermayesi Yatırım Ortaklığı A.Ş.',
    'IDGYO': 'İdealist Gayrimenkul Yatırım Ortaklığı A.Ş.',
    'IHEVA': 'İhlas Ev Aletleri İmalat Sanayi ve Ticaret A.Ş.',
    'IHYAY': 'İhlas Yayın Holding A.Ş.',
    'INTEK': 'İntek Bilgi İşlem Teknolojileri A.Ş.',
    'ISATR': 'İş Bankası A Grubu',
    'ISBIR': 'İşbir Holding A.Ş.',
    'ISBTR': 'İş Bankası B Grubu',
    'ISGLK': 'İş Girişim Sermayesi Yatırım Ortaklığı A.Ş.',
    'ISIST': 'İşbir Sentetik Dokuma Sanayi A.Ş.',
    'ISSEN': 'İşbir Sentetik Dokuma Sanayi A.Ş.',
    'ISYAT': 'İş Yatırım Ortaklığı A.Ş.',
    'IZINV': 'İz Yatırım Holding A.Ş.',
    'KENT': 'Kent Gıda Maddeleri Sanayi ve Ticaret A.Ş.',
    'KERVN': 'Kervansaray Yatırım Holding A.Ş.',
    'KLNMA': 'Türkiye Kalkınma ve Yatırım Bankası A.Ş.',
    'KRDMA': 'Kardemir Karabük Demir Çelik Sanayi ve Ticaret A.Ş. (A)',
    'KRDMB': 'Kardemir Karabük Demir Çelik Sanayi ve Ticaret A.Ş. (B)',
    'KRTEK': 'Karsu Tekstil Sanayi ve Ticaret A.Ş.',
    'KSTUR': 'Kuştur Kuşadası Turizm Endüstrisi A.Ş.',
    'KUVVA': 'Kuvva Gıda Ticaret ve Sanayi Yatırımları A.Ş.',
    'LUKSK': 'Lüks Kadife Ticaret ve Sanayi A.Ş.',
    'LYDYE': 'Lydia Yeşil Enerji Kaynakları A.Ş.',
    'MEGAP': 'Mega Polietilen Köpük Sanayi ve Ticaret A.Ş.',
    'MEPET': 'Mepet Metro Petrol ve Tesisleri Sanayi Ticaret A.Ş.',
    'MMCAS': 'MMC Sanayi ve Ticari Yatırımlar A.Ş.',
    'MTRYO': 'Metro Yatırım Ortaklığı A.Ş.',
    'MZHLD': 'Mazhar Zorlu Holding A.Ş.',
    'NPTLR': 'Netaş Pay Rüçhan Hakkı',
    'OBASE': 'Obase Bilgisayar ve Danışmanlık Hizmetleri Ticaret A.Ş.',
    'OPK30': 'Osmanlı Portföy BIST 30 Endeksi Hisse Senedi Yoğun BYF',
    'OPT25': 'Osmanlı Portföy BIST Temettü 25 Endeksi Hisse Senedi Yoğun BYF',
    'OPTGY': 'Optimum Yatırım Gayrimenkul Yatırım Ortaklığı A.Ş.',
    'OPTLR': 'Osmanlı Portföy TL Kısa Vadeli Borçlanma Araçları BYF',
    'OPX30': 'Osmanlı Portföy BIST 30 Endeksi Hisse Senedi Yoğun BYF',
    'ORCAY': 'Orçay Ortaköy Çay Sanayi ve Ticaret A.Ş.',
    'ORMA': 'Orma Orman Mahsulleri Entegre Sanayi ve Ticaret A.Ş.',
    'OYAYO': 'Oyak Yatırım Ortaklığı A.Ş.',
    'OYLUM': 'Oylum Sınai Yatırımlar A.Ş.',
    'OZRDN': 'Özerden Plastik Sanayi ve Ticaret A.Ş.',
    'PAMEL': 'Pamel Yenilenebilir Elektrik Üretim A.Ş.',
    'PRZMA': 'Prizma Pres Matbaacılık Yayıncılık Sanayi ve Ticaret A.Ş.',
    'PSDTC': 'Pergamon Status Dış Ticaret A.Ş.',
    'QNBFK': 'QNB Finans Finansal Kiralama A.Ş.',
    'QNBTR': 'QNB Bank A.Ş.',
    'QTEMZ': 'QNB Portföy Temiz Enerji Değişken BYF',
    'RNPOL': 'Rainbow Polikarbonat Sanayi Ticaret A.Ş.',
    'RODRG': 'Rodrigo Tekstil Sanayi ve Ticaret A.Ş.',
    'SAMAT': 'Saray Matbaacılık Kâğıtçılık Kırtasiyecilik Ticaret ve Sanayi A.Ş.',
    'SANEL': 'Sanel Mühendislik Elektrik Taahhüt Sanayi ve Ticaret A.Ş.',
    'SANKO': 'Sanko Pazarlama İthalat İhracat A.Ş.',
    'SEKFK': 'Şeker Finansal Kiralama A.Ş.',
    'SEKUR': 'Sekuro Plastik Ambalaj Sanayi A.Ş.',
    'SEYKM': 'Seyitler Kimya Sanayi A.Ş.',
    'SILVR': 'Silverline Endüstri ve Ticaret A.Ş.',
    'SKYLP': 'Skyalp Finansal Teknolojiler ve Danışmanlık A.Ş.',
    'SNPAM': 'Sönmez Pamuklu Sanayii A.Ş.',
    'SODSN': 'Sodaş Sodyum Sanayii A.Ş.',
    'SONME': 'Sönmez Filament Sentetik İplik ve Elyaf Sanayi A.Ş.',
    'SUMAS': 'Sumaş Suni Tahta ve Mobilya Sanayi A.Ş.',
    'TDGYO': 'Trend Gayrimenkul Yatırım Ortaklığı A.Ş.',
    'TRHOL': 'Turkish Yatırım Holding A.Ş.',
    'TRILC': 'Türk İlaç ve Serum Sanayi A.Ş.',
    'TSGYO': 'TSKB Gayrimenkul Yatırım Ortaklığı A.Ş.',
    'TSKB': 'Türkiye Sınai Kalkınma Bankası A.Ş.',
    'UFUK': 'Ufuk Yatırım Yönetim ve Gayrimenkul A.Ş.',
    'ULAS': 'Ulaşlar Turizm Yatırımları ve Dayanıklı Tüketim Malları Ticaret A.Ş.',
    'USDTR': 'QNB Portföy Dolar Borsa Yatırım Fonu',
    'VANGD': 'Vanet Gıda Sanayi İç ve Dış Ticaret A.Ş.',
    'VKFYO': 'Vakıf Menkul Kıymet Yatırım Ortaklığı A.Ş.',
    'VKING': 'Viking Kağıt ve Selüloz A.Ş.',
    'YBTAS': 'Yibitaş Yozgat İşçi Birliği İnşaat Malzemeleri Ticaret ve Sanayi A.Ş.',
    'YONGA': 'Yonga Mobilya Sanayi ve Ticaret A.Ş.',
    'YYAPI': 'Yeşil Yapı Endüstrisi A.Ş.',
}

path = Path('lib/services/bist_stocks.dart')
text = path.read_text(encoding='utf-8')
new_text = text
for symbol, name in updates.items():
    old = f"{{'symbol': '{symbol}', 'name': '{symbol}'}}"
    new = f"{{'symbol': '{symbol}', 'name': '{name}'}}"
    if old not in new_text:
        old = f"{{'symbol': '{symbol}', 'name': '{symbol}'}}"
    new_text = new_text.replace(old, new)

if new_text == text:
    print('No changes applied.')
else:
    path.write_text(new_text, encoding='utf-8')
    print('Updated', len(updates), 'entries.')
